### ISSUE TITLE
Beeper output stops working after GPS lock in Inav 7.1.0

### ISSUE THREAD

**Issue by wchnflr** [iNavFlight/inav#10106]
## Current Behavior
Reddit thread posted by user u/HANENG18 that discovered this bug: https://www.reddit.com/r/fpv/comments/1d6agbk/inav_beeper_strange_behaviour_wgps/
At least 3 Redditors have confirmed this bug.

## Steps to Reproduce
1. Assign a TX switch to the Beeper function in Modes tab.
2. TX switch turns on/off the external beeper at power up, but before GPS lock is satisfied.
3. Once GPS lock is satisfied, the external beeper no longer sounds. The ESC motor beepers still work.
4. Reset or power cycle the FC - the external beeper works again before GPS lock is satisfied.

## Expected behavior
The Beeper function will work regardless of GPS lock status.

## Suggested solution(s)
Free the beeper function from GPS lock status.

## Additional context
- FC Board name and vendor: Various, including:
1. Flywoo Goku GN405 Nano: target FLYWOOF405PRO
2. Flywoo Goku GN405S AIO: unofficial target FLYWOOF405S_AIO
3. Speedybee F405 v4: target SPEEDYBEEF405V4
- INAV version string: 7.1.0

**Comment by breadoven** [comment]
I probably don't have this issue using the current master build. I say probably because I thought I randomly wasn't getting the GPS ready beeps sometimes. However, when I checked the other day the beeper worked as expected.

You need to provide a Diff(s) to see if there's any common cause that might be causing the issue in your case.
