### ISSUE TITLE
Free mag alignment

### ISSUE THREAD

**Issue by Viald** [iNavFlight/inav#1029]
Is it possible to set any value to the mag alignment setting ?
The assembly of my quadcopter set the magnetometer to 135° CW but currently the only available values are 0, 90, 180 and 270°

![compass](https://cloud.githubusercontent.com/assets/3048030/21623633/9f3ace62-d203-11e6-9955-98352a3e5b37.gif)

**Comment by oleost** [comment]
Atm there is no "proper way of doing this. But there is somehow possible

![image](https://cloud.githubusercontent.com/assets/5670710/21623849/b96723de-d204-11e6-8e63-dad4e11fee56.png)

![image](https://cloud.githubusercontent.com/assets/5670710/21623855/c1bc70de-d204-11e6-9fc0-07a6b9dfed2a.png)

![image](https://cloud.githubusercontent.com/assets/5670710/21623861/cb7a9380-d204-11e6-87a7-a73c581ea0f0.png)

![image](https://cloud.githubusercontent.com/assets/5670710/21623869/d46889fc-d204-11e6-82da-a1f94e72fcda.png)


You could try and report back.

But seeing as your atleast the 3. guy asking for this it may be sensibile to allow setting a custom value?

So instead of fixed values in CLI, it would be freely adjustable, and then have the configurator only list the common ones as it currently is ?.



https://www.rcgroups.com/forums/showpost.php?p=36422701&postcount=9639

https://www.rcgroups.com/forums/showpost.php?p=36423155&postcount=9646

https://www.rcgroups.com/forums/showpost.php?p=36423422&postcount=9651

https://www.rcgroups.com/forums/showpost.php?p=36423488&postcount=9653

**Comment by Viald** [comment]
Thanks for your feedback I'll give a try soon and report here.

**Comment by WaspFPV** [comment]
@oleost that will not work when the craft is tilted. Magnetic inclination can be as high as 60 degrees depending on where you live. There it will go wrong pretty quickly. The FC needs to know that the sensor is rotated 45 degrees. Proper solution would be free adjustment as OP asked, or maybe just add more options for 45 degrees. Mag calibration works on sensor axes, not craft axes, and is applied before applying alignment, so it should work.

**Comment by digitalentity** [comment]
Mag is read at a fairly low rate so more options transformation shouldn't tax us too high. We can also add an option to mount the mag at a 90deg vertical angle (i.e. if FC is mounted vertically and mag/GPS is horizontal)

**Comment by Viald** [comment]
After calibration, the behavior of the mag is very very strange, sometime it's stable, something not, without trying to fly, just laid on the table...

**Comment by oleost** [comment]
The most versitale solution would probably be to add:

> align_mag_roll = 90
> 
> align_mag_pitch = 0
> 
> align_mag_yaw = 90
> 

This would also fix #86 

Could make so configurator only shows current values, but more advanced are allowed with CLI.

**Comment by Viald** [comment]
Would be nice :)

**Comment by Viald** [comment]
Could it be fixed ?

**Comment by Viald** [comment]
Any chance to have a fix or a workaround ?

**Comment by csurf** [comment]
What's the status on this? I urgently need a fix for a mag sensor that's mounted on a flying wing (popwing). The sensor is aligned parallel with the leading edge of the wing, while the FC is mounted "normally", with arrow pointing forward toward nose of plane. I need the ability to set an arbitrary angle for sensor X and Y axes.

**Comment by digitalentity** [comment]
I'll tackle this once we have 1.6 out of the door

**Comment by csurf** [comment]
how difficult would it be to implement this? How soon can a patch be developed? I'd be willing to compile & test a patch if you can come up with something quickly.

This will put a couple of my builds on hold, as the mag is at an angle on both wings.
Is there currently any issue with disabling mag on fixed-wing?

**Comment by WaspFPV** [comment]
@csurf Fixed wings can fly with gps only (no mag). Since fixed wing flies forward all the time, it can derive its course to a heading. Some people also use gps only for altitude (no baro)

**Comment by Buzzliteyear** [comment]
Just finished a build and needed a custom Mag alignment if this is possible Please, happy to do the testing

https://youtu.be/GXctoWFttoY?t=3m56s

**Comment by giacomo892** [comment]
@Buzzliteyear you may want to share the code via a pull request :)

**Comment by Buzzliteyear** [comment]
@giacomo892  I was brought up with Dos6.0 and find github 10 times harder to use but i shared in pull request hope its correct

**Comment by giacomo892** [comment]
I don't see any pull request in the list. Just upload your code branch to your GitHub and then from the website do a pull request against development branch.

**Comment by Buzzliteyear** [comment]
Ah that's because i dont know what to do ..........I wish so much your comments were easy to follow but its not sorry..

**Comment by giacomo892** [comment]
Just send the modifications and i'll do the pull request for you or otherwise read https://github.com/iNavFlight/inav/blob/master/docs/development/Development.md

**Comment by Buzzliteyear** [comment]
heres the file at the end thanks
https://www.rcgroups.com/forums/showthread.php?2914402-BiCopter

**Comment by giacomo892** [comment]
That's the compiled hex. We need the source code :)

**Comment by Buzzliteyear** [comment]
I dont have it going that is why im asking how to request the feature

**Comment by fiam** [comment]
For anyone else having this problem, here's a temporary workaround. The angle of rotation is hardcoded to 45º CW in the YAW axis, but should be pretty easy to modify the code to change your needs.

```diff
diff --git a/src/main/sensors/compass.c b/src/main/sensors/compass.c
index 5ef02d60..09e0673b 100644
--- a/src/main/sensors/compass.c
+++ b/src/main/sensors/compass.c
@@ -346,7 +346,13 @@ void compassUpdate(timeUs_t currentTimeUs)
         }
     }
 
-    alignSensors(mag.magADC, mag.dev.magAlign);
+#define SIN_M45 (-0.70710678118)
+#define COS_M45 (-(SIN_M45))
+    const int32_t x = mag.magADC[X];
+    const int32_t y = mag.magADC[Y];
+    mag.magADC[X] = x * COS_M45 - y * SIN_M45;
+    mag.magADC[Y] = x * SIN_M45 + y * COS_M45;
+    // alignSensors(mag.magADC, mag.dev.magAlign);
 
     magUpdatedAtLeastOnce = 1;
 }
```

**Comment by fiam** [comment]
@digitalentity Since I'm now suffering this problem, I'm interested in fixing it so I don't have to keep using custom builds on my Mini Talon. Could we get some conversation going about how we should solve it?

I'd say these days the magnetometer is the only sensor very likely mounted outside the FC, so it's not worth to change the way we handle alignment of all sensors. Instead, I like @oleost's suggestion in https://github.com/iNavFlight/inav/issues/1029#issuecomment-270761469, which consists in introducing 3 new settings, one for each axis of rotation.

**Comment by Buzzliteyear** [comment]
yes in 1 degree increments on the three axis is fine so it can be tuned once installed
