### ISSUE TITLE
Support for RP2350

### ISSUE THREAD

**Issue by akhodeir** [iNavFlight/inav#10392]
## Current Behavior
No support of Raspberry Pi Pico boards.

## Desired Behavior
Support of RP2350

## Suggested Solution
Raspberry PI announced RP2350 which is more powerful than RP2040
it has:

- Dual Arm Cortex-M33 cores with hardware single-precision floating point and DSP instructions @ 150MHz.
- 520 KB on-chip SRAM
- 30 or 48 GPIO
- ... More
- it is much cheaper than equivalent STM32 microcontrollers.

## Who does this impact? Who is this for?
it is much cheaper than equivalent STM32 microcontrollers and more available. 

## Additional context
Reference : https://www.raspberrypi.com/products/rp2350/

**Comment by sensei-hacker** [comment]
Being able to run INAV on the Pico 2 would be cool. It would be nifty. Porting it would be a big job, though.

One would of course need to add all of sensors, a low-noise power supply circuit, etc to build a flight controller. So from a *practical* perspective it would be a lot of effort in order to achieve something that's less usable than an existing $20 flight controller.

This probably isn't a project that any of the core INAV devs are likely to take up. If @akhodeir or someone else wants to give it a shot, we can help answer questions about INAV that come up.

**Comment by b14ckyy** [comment]
Surely an interesting Project but I agree, nothing for the main INAV Repo/Code. I will move this to discussion.
