### ISSUE TITLE
Set SafeHome point on the fly

### ISSUE THREAD

**Issue by DanielOBenson** [iNavFlight/inav#10437]
## Current Behavior
Safehome (or waypoint mission) is necessary for the autoland to work.  At the present time it's necessary to manually enter safehome points in the cli.

## Desired Behavior
It would be great to record a safe home point while flying over it.  Just like home reset works now.

## Suggested Solution
Enable recording a safe home point using a switch.   

## Who does this impact? Who is this for?
This would impact people who are flying any aircraft and who want to use the autoland feature.

## Additional context
THANK YOU!

**Comment by MrD-RC** [comment]
Safe homes are not designed to be used like that. They are supposed to be nearby to the home point. So that you can physically get to the safe home and ensure that it is safe for your aircraft to land. I.E, there are no people there who may get hit by the aircraft. This system is not intended for landing away from home.

**Comment by stronnag** [comment]
It is also possible to plan safehomes in both the INAV Configurator
![image](https://github.com/user-attachments/assets/329550dc-6ecf-444a-91fb-41b386015e67)
and mwp
![Screenshot From 2024-10-28 20-18-23](https://github.com/user-attachments/assets/52053618-4d0e-4446-bee5-cf8981e70dac)
so there is absolutely no need to either edit a CLI diff or have an in-flight method.

**Comment by DanielOBenson** [comment]
THANK YOU!
________________________________
