### ISSUE TITLE
Disarmed by Failsafe when the aircraft should entered have RTH

### ISSUE THREAD

**Issue by MrD-RC** [iNavFlight/inav#10483]
There have been a couple of reports where people have experienced a failsafe and the aircraft immediately disarms. An example of this can be found on the [INAV Fixed Wing Group on Facebook](https://www.facebook.com/1736758230/videos/563692736615847/). In the example, the aircraft autolaunches. As soon as it exits autolaunch, there is a failsafe. But instead of actioning RTH. The aircraft disarms. This aircraft was running TBS Crossfire, and had been working fine before. The only change being an update of the Crossfire firmware. However, there has also been a similar incident with an aircraft using ELRS. Both times the failsafe procedure was set to RTH.

It is unknown if this is an INAV issue, or related to the link. This is an information compilation at the moment. To try and find some correlation on what is happening.

If this has happened to you. Please could you reply to this issue giving as much detail as possible on your setup and what happened. If possible please include the following details (copy and paste this list as a template if it's easier):
- INAV Firmware version:
- Flight Controller hardware and target:
- Transmitter hardware and firmware version:
- Receiver hardware and firmware version:
- Failsafe setup on the receiver (if possible):
- Link to DVR footage with OSD overlaid:
- Text file containing the `diff all` from the flight controller
- Text file containing the Blackbox log from the flight:

If you cannot provide the DVR with OSD. Please include a description of the flight. If you could not recover the aircraft. A backup diff from before the flight will be fine. If you're not sure how to add your diff as a text file. Check out [this video](https://www.youtube.com/watch?v=Eul5BLyLoP0&t=980s).

### Example form:
- INAV Firmware version: INAV 7.1.2
- Flight Controller hardware and target: Matek H743-WING v3 - MATEKH743
- Transmitter hardware and firmware version: TBS Crossfire full size 6.17
- Receiver hardware and firmware version: TBS Crossfire Micro 6.17
- Failsafe setup on the receiver (if possible): Failsafe set to Cut
- Link to DVR footage with OSD overlaid: < link to youtube video >
- Text file containing the `diff all` from the flight controller <diff.txt>
- Text file containing the Blackbox log from the flight: <Blackbox.txt>

**Comment by ELLIOTfpv11** [comment]
I'm One of the people mentioned in the post. T

https://github.com/user-attachments/assets/b2a41b76-2c87-46e6-95d0-697437d00708

o be honest i never found the plane so i never been able to check the log and if i really setted everything correct, especially the failsafe page. once of the possible explanation still be i selected "DROP" instead of "RTH" but i still can't be sure about it.
note: after many hours of flight with the same plane i decided to test the rth in case of failsafe. i was 15 km out and 1500mt high. using elrs 2.4. i used my hand and i grabbed the elrs tx antenna pointing the radio to the ground. i finally get the failsafe but instead of entering rth i saw what you see in the video. Using digital i losted video link and i never recovered also the rc link. Later i found my elrs doesn't regain the link if tx and rx are not in the same rate mode and i changed rx from 50hz to 250 without doing the same on the tx. in my opionion the question now is how a failsafe can disarm the plane during a flight. i think it's not a glitch of the ch5 cause in this case it should be described as a "disarmed by switch", not "by failsafe".

**Comment by MrD-RC** [comment]
@ELLIOTfpv11 could you please answer the bullet point questions. Answering as much as you can.

**Comment by egpurush** [comment]
I had this incident and the video in facebook is from my MiniTalon Model.  I had flown this Model to the max distance of 7-8Km and to the altitude of 1Km before this incident. I had just updated my crossfire micro TXv2 and nano Rx from v6.09 to v6.36. My model is running INAV 6.1.1 and failsafe set to RTH, a perfect takeoff with autolaunch and when I took control of the model at 500m distance and 300 m height immediatly failsafe was triggered,it looks like I lost Rx link and the got DISARMED mid flight, which is strange as I have set failsafe to RTH. Luckly my spotter was having the model LOS and guided to safe landing.Unfortunately I lost the video link also when failsafe was trigger as I was not  facing the googles in correct direction. 
The question is why the Model was DISARMED instead of RTH when failsafe was triggered. attaching the video and Inav logs.

INAV Firmware version: INAV 6.1.1
Flight Controller hardware and target: Matek F405 wing v1
Transmitter hardware and firmware version: RadioMaster Tx16s
![faillsafe_cut](https://github.com/user-attachments/assets/0ce1a5f5-764b-4c1d-87fa-1ebf286b80b3)
![failsafe_rth](https://github.com/user-attachments/assets/1d1a6f17-529d-415d-b526-14dd9365f8e9)
 with Crossfire micro Txv2  with stock immortal T antenna and firmware v6.36
Receiver hardware and firmware version: Crossfire nano Rx with stock immortal T antenna and firmware v6.36
Failsafe setup on the receiver (if possible): Crossfire nano Rx set to "Cut"
Link to DVR footage with OSD overlaid:  Same video as in Facebook link above
Text file containing the diff all from the flight controller 
[Inav_disarm_diff_all.TXT](https://github.com/user-attachments/files/17928471/Inav_disarm_diff_all.TXT)
Text file containing the Blackbox log from the flight: 
[Inav_disarm_logs.TXT](https://github.com/user-attachments/files/17928473/Inav_disarm_logs.TXT)

**Comment by ELLIOTfpv11** [comment]
> @ELLIOTfpv11 could you please answer the bullet point questions. Answering as much as you can.

INAV Firmware version: INAV 7.0 or 6.1, i can't be sure
Flight Controller hardware and target: speedybee f405 wing
Transmitter hardware and firmware version: betafpv micro 2w module elrs 3.3.2 
Receiver hardware and firmware version: betafpv super d RX  elrs 3.3.2
Failsafe setup on the receiver (if possible): auto 
Link to DVR footage with OSD overlaid: see my First comment

**Comment by breadoven** [comment]
I think I can see what the problem is if the failsafe happens during launch. Launch mode isn't being cancelled properly when the failsafe occurs which prevents the switch to RTH flight mode before failsafe decides RTH has failed causing it to default to Emergency Landing instead ... which then defaults to Drop it because the emergency landing wasn't initialised correctly. So a couple of bugs it would appear.

In the log above the plane is still in launch mode when the failsafe occurs, 0.7s after the Rx signal is shown as lost. So this would tie in with the above bug.

However, this doesn't explain the other disarm in the 2nd post above when Launch mode wasn't active although it's not clear if RTH was actually set in that case.

**Comment by MrD-RC** [comment]
With the 2nd example (13km away). There is no diff or log. So we don't actually know what was set. Speaking on Facebook. He believes that it was set to RTH. But then there is no guarantee. Default is drop. So it could have been overlooked in the setup.

It sounds like there is something that can be fixed in the case of FS during auto launch. So that's a positive.

**Comment by breadoven** [comment]
I've fixed the RTH issue including have it fall back to Emergency Landing if RTH fails rather than falling back to Drop it. However, it still disarms when you have it set to Land and you get Failsafe during launch. Works OK once Launch has ended but not during Launch which is a bit strange ... need to work out why because it should really just behave the same way as RTH but Land instead.

**Comment by egpurush** [comment]
> @egpurush thank you for that. But could you please add the video here. There are a few developers who don't use Facebook.

Here is the youtube link [https://www.youtube.com/watch?v=9Fq75k-Zqnc](url)

**Comment by MrD-RC** [comment]
Testing in HITL shows that if `FAILSAFE` is set to `DROP`. You will see exactly what @ELLIOTfpv11 saw. So due to a lack of diff. I think we can put it down to that at the moment. However, if any data to the contrary turns up. It would be great to know about it. It's great that the other issue was found and is getting sorted.

**Comment by b14ckyy** [comment]
@MrD-RC did you replicate the issue or anyone else so we can verify if the fix works?

**Comment by MrD-RC** [comment]
Not the autolaunch issue. Only confirmed what happens with drop + failsafe.

**Comment by breadoven** [comment]
I tested the fix in HITL and it worked as expected. But always better if someone else can double check.

**Comment by egpurush** [comment]
Is to possible to build an image with fix on 6.1.1 version  or patch file that can be tested in INAV 6.1.1?

**Comment by b14ckyy** [comment]
Nope. INAV is a cumulative development. We don't maintain parallel versions. 
Not even sure if that bug is present in 6.1.1 at all.

**Comment by egpurush** [comment]
> Nope. INAV is a cumulative development. We don't maintain parallel versions. Not even sure if that bug is present in 6.1.1 at all.

Yes, it exists in 6.1.1 as reported above.

**Comment by MrD-RC** [comment]
The fix will be in 8.0.0 RC2 and later.
