### ISSUE TITLE
NAZA m8n gps on Naze32

### ISSUE THREAD

**Issue by smejfi** [iNavFlight/inav#1123]
Hey, I obviously didnt properly read the diferences between different m8n gps and instead of buying the one from UBLOX which has four pins for gps and another two for compas, I bought the one for NAZA, which has only four pins. Anyway, I want to use it on FC Naze32 rev6 and I found out that it works only with versions 1.1 or older. Can anyone explain me why and more importantly if its possible to make it work also on actual versions of inav? Thank you.

**Comment by oleost** [comment]
Hi, its due to size limitation of firmware.

Please read Wiki https://github.com/iNavFlight/inav/wiki/Getting-started-with-iNav#naze32-cc3d-and-other-f1-cpu-targets-restrictions

Also please use rc groups forum for user support https://www.rcgroups.com/forums/showthread.php?2495732-Cleanflight-iNav-(navigation-rewrite)-project

Closing this one.
