### ISSUE TITLE
Servo output broken in 857b3603c41e5faa8eb7f3c7a2b87f50f7143494

### ISSUE THREAD

**Issue by DzikuVx** [iNavFlight/inav#1139]
Servo output is completely broken in 857b3603c41e5faa8eb7f3c7a2b87f50f7143494

* MSP_SERVO frame reports 0 on all servo channels
* oscilloscope shows flat line on all servo lines on AirbotF4 and Omnibus targets

**Comment by oleost** [comment]
Can confirm issue on spracingf3 target using servo gimbal feature.

Looking at the "Motor" tab everything is at zero( 1500 is normal ) and looking at "Servos" tab CH1 is selected on all servos, and cannot change it. (Normal is none selected and then select the aux of choice ) Tried both Master configurator and 1.5.2, but the issue is with firmware 1.6

[dump 1,5.txt](https://github.com/iNavFlight/inav/files/717635/dump.1.5.txt)
[Dump 1,6.txt](https://github.com/iNavFlight/inav/files/717636/Dump.1.6.txt)
![motors working 1 5](https://cloud.githubusercontent.com/assets/5670710/22122856/c6c5d534-de89-11e6-95ca-25b38292a02b.PNG)
![motors](https://cloud.githubusercontent.com/assets/5670710/22122858/c6c7e6e4-de89-11e6-86ac-8814c56d12a3.PNG)
![servos is working 1 5](https://cloud.githubusercontent.com/assets/5670710/22122859/c6d11a98-de89-11e6-877a-a5ecd4343522.PNG)
![servos](https://cloud.githubusercontent.com/assets/5670710/22122857/c6c5b13a-de89-11e6-9a58-7abb60eb0a30.PNG)

**Comment by digitalentity** [comment]
Can confirm on latest `development` + airplane mixer. Servos are stuck at 1500 - no reaction to PID output or sticks.

**Comment by digitalentity** [comment]
Bisecting narrowed this down to bf46c4809f924392322b3997a2de4a04b1b1e4d5. @martinbudden can you have a look?

**Comment by digitalentity** [comment]
Hm... I can no longer reproduce the issue on latest `development`. Looks like I was barking up the wrong tree here.

**Comment by oleost** [comment]
@martinbudden Tried latest development today. Still no go on servo gimbal function. Motor tab is showing 1500us now however, but in the "Servos" Tab applying control over Servo 0 on Aux4 for example does not stick.

[dump and bootlog.txt](https://github.com/iNavFlight/inav/files/718848/dump.and.bootlog.txt)
http://pastebin.com/Satpbccu

( Also enabling live mode and trying to control servo doesnt work )

**Comment by stronnag** [comment]
Perhaps worth noting that servos have been broken in betaflight 3.1 for ages in case this is a result of a bf catch up.

**Comment by oleost** [comment]
@martinbudden Did retest today. 
Still no go at servo gimbal feature.

**Comment by martinbudden** [comment]
OK, I'll try and look at this later in the week.

**Comment by digitalentity** [comment]
@martinbudden did you by any chance look at this issue?

**Comment by martinbudden** [comment]
@digitalentity , no I haven't had a chance to look at this. Can you do this?

**Comment by digitalentity** [comment]
I'm afraid that don't have SPRacingF3 target to test. I'll have a dig into my FC box.

**Comment by digitalentity** [comment]
Tested on CC3D - works fine (both QuadX and Flying wing config).
@oleost can you re-test and if issue persists for you - open a new one for your specific configuration?

**Comment by oleost** [comment]
@digitalentity it's was specifically servo gimbal feature that did not work on spracingf3.

I have screwed together my quad again without servo to test this more. If someone else have an loose spracingf3 and a servo it would spare me some work testing this again.

**Comment by DzikuVx** [comment]
Also tested for SERVO_GIMBAL for SPRF3. Works in 5c2f2f9af333685d24da7a4187fab8ada4019b9e

**Comment by oleost** [comment]
Great, probably been fixed someplace
