### ISSUE TITLE
Preset PID of Flying Wing Z84 are not correct

### ISSUE THREAD

**Issue by isilcala** [iNavFlight/inav#1347]
Preset value of P_PITCH & P_ROLL are both 2, should be 20 I suppose?

**Comment by digitalentity** [comment]
No. PIDs are correct for 1.6.

**Comment by isilcala** [comment]
but for 600mm flying wing those Ps are 20?

**Comment by digitalentity** [comment]
With PIFF controller there are different ways to achieve a good tune. Presets are what people ended up with for their aircrafts

**Comment by Schalonsus** [comment]
I can confirm for planes you should use low P values and therefore higher FF

**Comment by isilcala** [comment]
Z84 and 600mm wings are pretty close things, if with PIFF controller, 2 is the right value for Z84, then for 600mm wings the default P should be 2 as well? it seems one of the preset value is incorrect (probably the 600mm wing?).

**Comment by Schalonsus** [comment]
With my 1.2m wing i have P-Pitch = 7 and P-Roll = 17
But i looked at my BB log and saw that i need to reduce P-Pitch a little bit and P-Roll a lot.
So i will try P-Pitch = 5 and P-Roll = 8 next time

**Comment by oleost** [comment]
@isilcala As Digitalentity pointed out there are different ways to archieve a good tune with PIFF.

Yes 600mm and Z84 are close, but two different people have tuned theyr aircrafts.
One where P-gain does alot of work, and the other one where FF-gain does it.

I ( I made the Z84 preset ) prefer to have the FF-gain do most if it, as it will mimick more flying in passthrough but with added stabiliation.

Also it will be less stressfull on the servo,because the way plane behaves with high P-gain vs high FF-gain.

**Comment by isilcala** [comment]
Good to know those values are intentionally set and correct. I thought there might be a mistake to see such a big difference in values but good it's not the case. Very appreciate you guys created the PIFF controller for airplanes, can't wait to try it out!
