### ISSUE TITLE
FW - Possibility to have airplane always ARM'ed 

### ISSUE THREAD

**Issue by digitalentity** [iNavFlight/inav#138]
Some safety measures must be considered:
- MOTOR_STOP must be selected
- Home position should be set when GPS is firstly acquired

**Comment by oleost** [comment]
How to handle failsafe?

Example for me: when the TX and RX are close I loose the RC link( bending over to pick-up plane ). Because it's disarmed it's doesn't enter failsafe RTH in this case.

How to minimize risk of this happening with always armed? Since you often land some distance from home.

How do other FC do this?

**Comment by oleost** [comment]
*doesn't enter failsafe stage 2

**Comment by melkati** [comment]
Others FC have into account speed and height (if speed < x kmh or eight bellow x meters doesn't engage RTH).

**Comment by melkati** [comment]
Others FC have into account speed and height (if speed < x kmh or eight bellow x meters doesn't engage RTH).

**Comment by melkati** [comment]
Others FC have into account speed and height (if speed < x kmh or eight bellow x meters doesn't engage RTH).

**Comment by oleost** [comment]
#310 

Maybe close this and let #310 take it forward?
