### ISSUE TITLE
Aerial 3D mapping

### ISSUE THREAD

**Issue by LucasFPV** [iNavFlight/inav#1590]
Hello, 
Would be great to add the feature in INAV with mission planner to take at selected moments a picture from a camera (servo output to send signal to the camera) to then create a 3D Aerial Map. 
Something similar as the APM feature would be great!
Regards,
Lucas FPV  
Example: https://www.youtube.com/watch?v=2ZsO3LWtd9g

**Comment by digitalentity** [comment]
Probably won't happen any time soon.

**Comment by oleost** [comment]
Could it be implemented simple?

Take picture every X second on Hardcoded to channel 20 when featue is enabled. Then to use you simple forward CH 20 to an aux channel. ( Taking pictures just mean taking CH20 to 2000us )

Could addiotionl be configured to take picture every waypoint instead of time based.

**Comment by LucasFPV** [comment]
Yeah, we could set a switch to toggle during flight and with an already planned (Mission planner) route, it would activate via an RC servo output pin for example the gorpo shutter each Number of seconds. Found this stuff which is compatible with the gopro wifi to convert an rc servo input to activate the shutter. https://www.youtube.com/watch?v=t-QeQ9M0KKg

**Comment by oleost** [comment]
Btw if you own an advanced radio like taranis you can simple do this by
radio, program it go high every x second while switch is active.

9. jul. 2017 4.07 p.m. skrev "LucasFPV" <notifications@github.com>:

Yeah, we could set a switch to toggle during flight and with an already
planned Mission planner route, it would activate via an RC servo output pin
for example the gorpo shutter each Number of seconds. Found this stuff
which is compatible with the gopro wifi to convert an rc servo input to
activate the shutter. https://www.youtube.com/watch?v=t-QeQ9M0KKg

—
You are receiving this because you commented.

Reply to this email directly, view it on GitHub
<https://github.com/iNavFlight/inav/issues/1590#issuecomment-313921984>,
or mute
the thread

**Comment by LucasFPV** [comment]
Got an advanced radio but not good for FPV.. Futaba T18SZ

**Comment by nm17** [comment]
Any updates on this? Still need this feature

**Comment by myrcwing** [comment]
Following up to see if anything was updated for camera trigger in INav 3.0. Any plans for this to be added?

**Comment by nm17** [comment]
It would be great to have at least more info on external camera trigger technology. I'll try to connect my old digital camera to my drone and try to figure out stuff, **although** if anyone is reading this and is trying to try to do something like that themselves, don't rely on me delivering, I might forget about this issue again, maybe not.

**Comment by nm17** [comment]
@myrcwing can you provide a way to contact you? My email is `nm17@riseup.net` and it would be great to know yours, so we could figure things out together.

**Comment by nm17** [comment]
@LucasFPV you too

> @myrcwing can you provide a way to contact you? My email is `nm17@riseup.net` and it would be great to know yours, so we could figure things out together.
