### ISSUE TITLE
inav 1.7.0 By Omnibus F4 Pro OSD wrong 

### ISSUE THREAD

**Issue by hsu6328** [iNavFlight/inav#1745]
The latitude and longitude displayed in the OSD of Omnibus F4 Pro is wrong(INAV 1.7.0)

**Comment by jstremmler** [comment]
Cant confirm that! 

Can you mail a picture from the OSD and a screenshot from the configurator GPS position?

**Comment by StewLG** [comment]
There has been at least one fix applied to invalid display of lat/long since 1.7.0. Although it doesn't (currently) show up in the release notes, 1.7.1 should include this correction:

https://github.com/iNavFlight/inav/pull/1676

So, please try it again with 1.7.1. If you are still having problems, please post a screen shot, and tell us what lat/long *should* be displayed.

**Comment by hsu6328** [comment]
I have tested that the problem has been fixed in 1.7.1，thanks

**Comment by StewLG** [comment]
Great! Glad to hear it fixed your problem.

You should now close this issue.

**Comment by digitalentity** [comment]
Since it's fixed, I'm closing this one.

**Comment by StewLG** [comment]
@digitalentity, it would be good to edit the 1.7.1 release notes and mention that this bug has been fixed.

I would submit the change myself, but I'm not sure how. The release notes don't appear to be part of the repo, and it's not a wiki page either. (If I can make/submit an edit, tell me how and I'll do it.)

**Comment by digitalentity** [comment]
@StewLG  agreed, release notes edited.
