### ISSUE TITLE
Improvement of Automatic Landing in RTH

### ISSUE THREAD

**Issue by raul-ortega** [iNavFlight/inav#1814]
Perhaps it is a crazy idea, but in my community we have been discussing about how to improve the precision in automatic landing trying to avoid crashes with the objects arround the home position. Please, read this issue like that, some ideas that we hope to be no much dificult to implement.

The image bellow shows in some way what could be a better procedure for the automatic landing:

![image](https://user-images.githubusercontent.com/12935392/27435425-85643f58-575c-11e7-81e0-0991af417989.png)

It is based on the actual procedure, but adding two new components: The circular descent is performed until the aircraft reaches a minimum altitude. After that, it navigates through waypoints  to line the runway (real or virtual) and lands.

I'll try to explain better the full procedure:

0.- Define the virtual runway:

- Previous to take off the user places the aircraft on a point that could be considered the runway header. He connects the battery and home position is set (waypoint H).
- The user switches on with the transmiter to a mode that could be called "RUNWAY mode". 
- Then, the user walks to another point with the plane in his hand, taking into account the direction of the wind, and also considering that it is a safe path for the landing procedure, and with a stick combination, or perhaps pointing the nose of the aircraft to the sky, sets a waypoint (WP0).

This could help iNav to know the length and direction of a "virtual" runway.

1.- Take off:

- The user arms the aircraft and launch it to the air following the "virtual" runway, and flies.

2.- RTH and LOITTER

- When the user, or failsafe system, switches to RTH mode, the aircraft flies towards to WP3, which coudl be calculated automatically taking into account where the home position is set, and a radius.

- The aircraft starts to loiter with the defined radius and descend. Descent speed is limited to nav_landing_speed when altitude is above nav_land_slowdown_maxalt.

3.- Approximation 

- When nav_land_slowdown_maxalt is reached, the aircraft flies to WP2 keeping the altitude constant.

- And continues flying to WP1 keeping the altitude constant, with the aim of line the runway.

- WP2 and WP1 are calculated automatically by iNav taking into account the position, direction, and size of the runway, as well as the altitude and speed needed/configured for the landing procedure.

4.- Landing 

- When WP1 is reached, vertical speed is scaled down to one fourth of nav_landing_speed at nav_land_slowdown_minalt.

- Once Home position is reached, motor is stopped, and the aircraft glides until it lands.

I hope I have expressed the idea well and could be implemented as an improvement or an alternative to the current procedure.

**Comment by skaman82** [comment]
> The user arms the aircraft and launch it to the air following the "virtual" runway, and flies.

That could be problematic because the launching direction is often depending on the wind situation. If you have a location with predefined landing area, the chances that the "virtual runway" aligns with launch direction are very slim.

![bildschirmfoto 2017-06-22 um 16 05 05](https://user-images.githubusercontent.com/11768024/27438212-c394a12a-5764-11e7-8009-21b461261065.png)

**Comment by digitalentity** [comment]
Initially I think we can just come in for a landing in the opposite direction we launched. I.e. if we launched due North, we'll come in for a landing due South and will aim to land at the spot we launched from.

**Comment by DzikuVx** [comment]
@digitalentity I'd rather say take off and land into the wind. So landing should be the same as take off

**Comment by digitalentity** [comment]
@DzikuVx this must be configurable. Where I fly you usually don't have much choice - there's city behind and turning for a landing over the buildings is less safe than landing in the opposite direction you launched.

**Comment by skaman82** [comment]
@DzikuVx yes it would make sense. But we know for sure that the launching direction is safe. So landing in opposite direction is safe also. In the picture above there is a road in the upper left corner. So if the plane would land in the launch direction, it would most likely crash into a moving car :)

**Comment by DzikuVx** [comment]
So let me quote someone:

> moah settings

**Comment by raul-ortega** [comment]
"Then, the user walks to another point with the plane in his hand, taking into account the direction of the wind, and also considering that it is a safe path for the landing procedure, and with a stick combination, or perhaps pointing the nose of the aircraft to the sky, sets a waypoint (WP0)."

I think it doesn't matter in which direction you launch the aircraft if you set this waipoint in the previous instant to take off, taking into account the direction of the wind (for example, let's supposed that I know that the wind will not change too much during next 20 minutes in my flying filed) ... With the home waypoint and this wp0 waypoint, the virtual runway is defined in the oposite direction of the wind. When landing are known the position, length and direction of the runway (which is the oposite direction of the wind).

**Comment by digitalentity** [comment]
@raul-ortega yes, this is definitely a good procedure. However, what if user redefines "home" in flight using "HOME RESET" mode? What if user doesn't define WP0 and hit RTH? We need a solution that will work in all cases (or at least as many cases as possible).

**Comment by raul-ortega** [comment]
@digitalentity if WP0 is not defined, the landing should proceeds by default in loitter, just like now.

**Comment by raul-ortega** [comment]
Also, in case of HOME RESET, default procedure for landing wolud be executed.

**Comment by hali9** [comment]
I think it is possible to approach without defining waypoints by defining a virtual point for the approach.
The landing route begins at the home point and is directed at homepoint.yaw.
These items are saved during arming or during HOME_RESET.
It allows to take off in any direction and land in any designated direction.
Scenario:
1. Turn on RTH.
2. When the height falls below maxalt during circulation, keep the maxalt height until you reach homepoint.yaw + 135deg (decision point)
3. Calculate the virtual approach point and lower the height around this point until you reach the minalt.
4. Keep the minalt height until you reach homepoint.yaw direction.
5. Land using the angle mode with roll = 0 and pith = dive_angle (as it is now).
![inav](https://user-images.githubusercontent.com/23119651/41711516-8c3aa6ae-7548-11e8-888b-315bd254efdd.png)

**Comment by hali9** [comment]
I did some tests some completed successfully and a few changes are needed.
1. A variable with a landing direction is needed, with a predefined land_direction. It is also required that only the homereset could change it.
2. Need to separate the minalt. Land with aproach should not use minalt. I suggest safe_alt - the height from which the last approach is made, motor_off_alt - the height of engine shutdown.
3. Also need a variable length approach aproach_distance. Because determining the length of the approach based on loiter_radius is usually insufficient.
4. When is wind, I have a problem with maintaining the height in poshold. At high altitude, it does not matter, but during the course of the approach yes. One solution is min_alt > safe_alt, but this does not fully solve the problem. Use yaw instead of roll for navigation is very good in this case (https://github.com/iNavFlight/inav/issues/3817).
5. The whole approach should be done in the (loiter_radius / TAN_15DEG) circle. After exceed this border, the plane should go to RTH again (again approach), so aproach should be reset.
6. nav_rth_allow_landing should be expanded:
 - NEVER - never land
 - ALWAYS - always land
 - APROACH - always land with aproach
 - FS_ONLY - Allow landing only if RTH was triggered by failsafe
 - FS_ONLY_APR - Allow landing with aproach only if RTH was triggered by failsafe
 - FS_NO_APR - Allow landing with aproach, but if RTH was triggered by failsafe land without aproach

but that is a lot of "if", maybe we need split it in two:
nav_rth_allow_landing (no, yes, aproach)
nav_failsafe_allow_landing (no, yes, aproach)

**Comment by wx4cb** [comment]
also something that just came up in a flying session today. if an aircraft has retracts, would it be possible to automatically extend them below a certain alt that way for some that are pushers, you don't get a prop strike (or worse, a smashed underslung camera gimbal.

**Comment by bishko** [comment]
> @digitalentity I'd rather say take off and land into the wind. So landing should be the same as take off

Yes Pawel, but the wind can change in a stort time and definitely changes after a 1h flight for example.

**Comment by bakwc** [comment]
Sorry, why does it closed? Is this feature implemented?

**Comment by MrD-RC** [comment]
It will be in the future. It is currently being developed, before being merged in to the main branch.
