### ISSUE TITLE
How to turn on SONAR with iNav 1.7.1?

### ISSUE THREAD

**Issue by liutairan** [iNavFlight/inav#1817]
Just like another post, I cannot find SONAR configuration. I also tried to use CLI feature SONAR, but it shows that invalid command. Is it removed again?

**Comment by liutairan** [comment]
I saw that sonar was back in 1.7, but cannot find it in the configurator.

**Comment by stronnag** [comment]
have you specified the sonar hardware ?
````
set rangefinder_hardware = 
Allowed values: NONE, HCSR04, SRF10
````

**Comment by johnsilvester** [comment]
@liutairan  Yeah! use @stronnag  command in the CLI to activate it!

**Comment by stronnag** [comment]
Not sure if SURFACE mode is working though. A brave test volunteer?

**Comment by johnsilvester** [comment]
I'll test it out in the next day or two

**Comment by liutairan** [comment]
@stronnag @johnsilvester Thanks~ Just found it. I will test it when the weather get better.

**Comment by nerezw** [comment]
I connected an HC SR04 to my spracingF3, entered the CLI command, SONAR tab turns red and nothing else.... any ideas?

**Comment by DzikuVx** [comment]
@nerezw we are not wizards or prohets, you have to be much more specific. How you connected and what you entered. CLI `diff` maybe?

**Comment by nerezw** [comment]
I have an spracingF3. I connected sonar trigger to IO2/5(yellow) and sonar echo to IO2/6(green) and 5volts Vcc on HC-SR04.
I entered :  # set rangefinder_hardware
and got
rangefinder_hardware = NONE
Allowed values: NONE, HCSR04, SRF10
and then

# set rangefinder_hardware = HCSR04
rangefinder_hardware set to HCSR04

and the save

the SONAR tab on the top of the screen turns RED
the SANAR tab in the sensors screen can not be selected

can any body help

**Comment by DzikuVx** [comment]
`diff` please. HC-SR04 works with INAV 1.7.1 since I tested it few days ago. So looks like you are doing something wrong after all

**Comment by nerezw** [comment]
Ok... Will have a close look

On Jul 6, 2017 13:09, "Paweł Spychalski" <notifications@github.com> wrote:

diff please. HC-SR04 works with INAV 1.7.1 since I tested it few days ago.
So looks like you are doing something wrong after all

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/iNavFlight/inav/issues/1817#issuecomment-313366581>,
or mute
the thread

**Comment by nerezw** [comment]
here is the diff when i go into cli
Am I missing anything

Entering CLI Mode, type 'exit' to return, or 'help'

# diff

# version
# INAV/SPRACINGF3 1.7.1 Jun  3 2017 / 08:13:23 (48e1feff)

# resources

# mixer

# servo

# servo mix

# feature
feature -RX_PPM
feature RX_SERIAL
feature GPS

# beeper

# map

# serial
serial 1 2 115200 9600 0 115200
serial 2 64 115200 38400 0 115200

# led

# color

# mode_color

# aux

# adjrange

# rxrange

# master
set acc_hardware = MPU6050
set acczero_x = 34
set acczero_y = 3
set acczero_z = -188
set accgain_x = 4098
set accgain_y = 4090
set accgain_z = 4082
set rangefinder_hardware = HCSR04
set mag_hardware = HMC5883
set mag_declination = -820
set magzero_x = -73
set magzero_y = -68
set magzero_z = 82
set baro_hardware = MS5611
set serialrx_provider = IBUS

# profile
profile 1


#

**Comment by johnsilvester** [comment]
Try soldering to the 'Trig' and 'Echo' pins on the bottom side of an spf3

**Comment by nerezw** [comment]
Will do... Thanks

**Comment by liutairan** [comment]
@nerezw Have you solved your problem? Did you use usb port to connect to the computer? If so, maybe you can try providing extra power to the board. At least for me, the board cannot provide enough power for the sonar if using USB connecting to computer. Once I have the battery connected or other power source connected, the sonar will work well; once I remove the battery, the sonar indicator will get red again.

**Comment by nerezw** [comment]
I haven't solved it yet.  I was going to try 1k resistors on tabs under the
board as suggested by someone

On Jul 7, 2017 22:33, "Tairan Liu" <notifications@github.com> wrote:

@nerezw <https://github.com/nerezw> Have you solved your problem? Did you
use usb port to connect to the computer? If so, maybe you can try providing
extra power to the board. At least for me, the board cannot provide enough
power for the sonar if using USB connecting to computer. Once I have the
battery connected or other power source connected, the sonar will work
well; once I remove the battery, the sonar indicator will get red again.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/iNavFlight/inav/issues/1817#issuecomment-313786136>,
or mute
the thread

**Comment by matevz25** [comment]
On cleanflight sonar works ok with 1k resistor on sda and sdl. I tried with inav cli enabled, doesnt work its red.
