### ISSUE TITLE
FW: blackbox rcCommand rate do not match axis rate

### ISSUE THREAD

**Issue by DzikuVx** [iNavFlight/inav#1824]
@digitalentity I observed something strange in 1.7.1 on fixed wing: rccommand rate do not match axis rate. Look here:

![image](https://user-images.githubusercontent.com/966811/27511390-dfe72f5e-5922-11e7-9686-1a6d38354bcc.png)
![image](https://user-images.githubusercontent.com/966811/27511392-f0ba451e-5922-11e7-9a1e-4318420e8415.png)

Roll rate set to 300dps, rcCommand requests 430, Iterm behaves like it wants to negate missing 130dps. Either log is wrong or rcCommand is not computed correctly and/or Iterm acts in wrong direction. I just do not get it...

[wing_v3_blackbox_log_2017-06-24_205106.TXT](https://github.com/iNavFlight/inav/files/1099969/wing_v3_blackbox_log_2017-06-24_205106.TXT)

**Comment by digitalentity** [comment]
Blackbox explorer maps rcCommand to [deg/s] incorrectly. It's more correct to observe `axisRate` variable which is PID controller setpoint. In your case at that specific point in time gyro rate is 348 deg/s and `axisRate` is merely 292 deg/s, so the wing overshoots the desired rate - that's why you see negative `P` and decreasing `I` - PI-part of the controller is compensating for overshoot.

**Comment by DzikuVx** [comment]
ok, thanks, moving to BB explorer project

**Comment by DzikuVx** [comment]
iNavFlight/blackbox-log-viewer#6
