### ISSUE TITLE
CRSF Telemetry not picking up RSSI/Link quality.

### ISSUE THREAD

**Issue by peeejayz** [iNavFlight/inav#1833]
As title, when running 2 way CRSF telemetery/control link inav doesn't pick up the RSSI/Link quality to put this into the OSD/UI

**Comment by Dronek** [comment]
RSSI, Link Qly and SNR are handled by the crossfire TX module, AFAIK.
In my case, all parameters are recognized by the Transmitter plus additional telemetry coming from inav.

You can send the RSSI (or combined RSSI/LQ) value as PWM over a free channel to iNav and set iNav to use this channel for incomming RSSI information. In order to do so, you have to map the respective channel via the crossfire module menu.

In my case, RSSI on PWM channel is correctly recognized by iNav and shown in the configurator as RSSI value **but my minimOSD is always stuck at RSSI = 100% despite being configured to use FC RSSI value.**
I don't know if this is related to iNav or mwosd but it was certainly working for quite a while.

**Comment by digitalentity** [comment]
Can't reproduce. RSSI/LQ is injected into RC channel correctly and picked up by INAV
