### ISSUE TITLE
No connection with SPRACEF3-MINI over USB

### ISSUE THREAD

**Issue by schuppenkarp** [iNavFlight/inav#1882]
I am not able to connect to the board with the newest Version 1.7.1 also older version starting with the 1.6 are not working. The USB VCP is correctly assigned to the flight control and the iNav Configurator also can open it but after 10 seconds the connection sequence ends because no configuration was received from the flightcontrol.

There should be no problem with the board because Cleanflight in the newest Version is working without any Problems on the same board ans same configuartion.

The User-LED is blinking on Startup 3xfast-pause-3x-VeryFast-Pause-2TimesFancy-pause-continouseBlinking

**Comment by tonyintn** [comment]
The problem is not Inav many including myself has never had a connect problem with the SP F3 on any build.  
I would start by checking your USB dongle and making sure you setting are correct also might check to see if your USB connect is actually working i.e. missing drivers.

Use the bootloader by bridging and reflash.

**Comment by schuppenkarp** [comment]
Board and usb are working 

I can flash clearflight and everything is working 

I have the spracer f3 mini

**Comment by tonyintn** [comment]
This is just a hunt in the dark but something to try; the mini has limited memory thus you could be running into a problem with that.  
Keep in mind iNav files uses more space than a cleanflight file as it has more going on internally.  
F3 built file has everything turned on and using the Normal F3 to the max; Rebuild your own F3 file but turn things off such as LEDs, Sonar, and/or blackbox this is just a test as you are probably maxing out the F3 mini. 
If that work one by one you can turn on items and rebuilt until you hit that ceiling.

**Comment by schuppenkarp** [comment]
i think the mini version is using the same uC as the SPRacing F3 (STM32F303CC) so i dont think so that the problem is in the flashsize. Is there anywhere a documentation of the blinkcode at the startup of the FlightControl? Or is there a way to get out some Boot Messages on one of the serial ports to find the problem?

Best Regards

**Comment by ShawnzAZ** [comment]
I'm able to Use 1.7.1 on a 'real' SPRacing F3 Mini (Not SPR F3) without issue.  I have GPS on UART2 and a MinimOSD on UART3.   I'm going to try to integrate a Bluetooth module on UART1 since I'm using PPM input.  I will collect some more info when I get home to see if I can help you get this sorted out.  Hopefully it's something you can fix up with Zadig.

**Comment by digitalentity** [comment]
Can't reproduce
