### ISSUE TITLE
OSD not showing good mode

### ISSUE THREAD

**Issue by voodou59** [iNavFlight/inav#2035]
Hi, a little bug that can be easily solved. When I activate RTH, OSD write accro mode instead and RTH works. I'm using Passthrough/Horizon/RTH. The first two are well displayed but not RTH.

Cheers.

**Comment by fiam** [comment]
@voodou59 How are you testing that? It seems to me that RTH mode is not engaging because you are testing either without a valid GPS fix our without enough distance from the HOME point (where you armed the model) or maybe without a valid heading (if you're using fixed wing without MAG you need to be moving at least at 3m/s).

**Comment by voodou59** [comment]
I was 200 meters away from home, 14 satellites.
I'm waiting for a LC Filter cause video signal is not so good but once I can make a video, I'll post a link.
Moreover, if you need a translator from english to french, I'm in.

**Comment by digitalentity** [comment]
Does RTH mode indeed activate? Do your plane turn home? What OSD are you using (also with what firmware)?

**Comment by DzikuVx** [comment]
Due to lack of progress and no signs of actual bug, I'm closing it. Thanks

**Comment by voodou59** [comment]
![vlcsnap-2017-10-07-21h03m15s621](https://user-images.githubusercontent.com/17965637/31311044-495eb078-aba4-11e7-8e26-95f733cb7178.png)
Sorry I was working. First image you can see the setup of aux2 with rth.
2nd you can see ACCRO when arming rth. Need to test RTH since new update but it still write ACCRO.
Best regards.

![rth](https://user-images.githubusercontent.com/17965637/31310985-126a58de-aba3-11e7-9bc1-64859a78ff96.png)

**Comment by fiam** [comment]
@voodou59 RTH will never engage on the bench. Note that the boxes only turn blue when the mode is active, not when you request it to be active. In order to enable RTH, model needs to be armed and flying.

Note also that the channel is outside the selected range, so it would never enable RTH with that channel in the current position and that configuration.

**Comment by voodou59** [comment]
Hi, ok thanks, I will try to record while flying to see it. The channel was only to show the good configuration as aux 2. When I switch it with radio it goes to RTH mode. Radio was off when I took the printscreen.

Thanks.

**Comment by fiam** [comment]
If moving the switch on the radio puts the small marker at the bottom between the ends of the slider, it will ask the FC to engage RTH mode. Note that it doesn't mean that the mode will actually active, since there are preconditions that must be satisfied. For example, you can't enable ACRO mode until the gyro has been calibrated (you can see this in the OSD when FC is booting up, mode will show as PASS).

On the other hand, the OSD will always show active mode(s).

**Comment by voodou59** [comment]
I tried it today, everything work good after a new update. Thanks for help. You can close it ;-)

**Comment by boruvka112** [comment]
Hi guys,I have similar problem with iNav osd on my Matek F405 wing SE,When i switch on RTH the OSD show AIR,or if i switch to Manual it showr again AIR, I usig firmware 2,5 and Configurator 2,5,0 .The Configurator show switching dots on the mode panel on correct possition but OSD say just AIR.So i am not sure if i can go to air? Can someone give me advice please?
Thank you Bob
