### ISSUE TITLE
Tweak artificial horizon indicator in OSD

### ISSUE THREAD

**Issue by giacomo892** [iNavFlight/inav#2189]
We should add the possibility to optionally transform the artificial horizon indicator into attitude indicator instead by basically reversing the actual displayed artificial horizon.

It will be nice as you immediately visually see how much your wing or multi is rolled.

**Comment by fiam** [comment]
@giacomo892 I've been thinking about this one and it seems the problem to me is that we're lacking an aircraft reference in the indicator, which makes it more difficult to visually see your angle to the ground. I've just made this quick and dirty hack which shows a schematic airplane rather than a crosshair in the middle of the OSD. What do you think about it?

<img width="492" alt="screen shot 2017-09-29 at 00 23 41" src="https://user-images.githubusercontent.com/41529/30994789-f0146a96-a4ad-11e7-8a0d-27b738f08f98.png">
<img width="423" alt="screen shot 2017-09-29 at 00 27 31" src="https://user-images.githubusercontent.com/41529/30994792-f44b3b94-a4ad-11e7-82fa-cbdafd95bb34.png">

**Comment by giacomo892** [comment]
@fiam Thanks for your precious work! It looks very neat, but do we really need the aircraft reference? Aren't the lateral arrows enough? I think this should provide enough reference for the purpose :) Like... "hey. i'm around 80 degrees now"

**Comment by fiam** [comment]
Fixed in #2234
