### ISSUE TITLE
FSK modem in software

### ISSUE THREAD

**Issue by OpticalNZ** [iNavFlight/inav#2221]
For sending LTM telemetry down the FPV audio channel without special modem hardware. Potentially using either a PWM output (with two base frequencies) or DAC output?

Implemented by the Aeroquad project developed code to generate the FSK output in software. Code here: https://github.com/AeroQuad/AeroQuad/blob/master/Libraries/AQ_SoftModem/AQ_SoftModem.h

_"The STM32 CPU is good enough to emulate a FSK modem by using one of its DACs (Digital Analog Converter). According to the sourcecode in AQ_SoftModem.h the softmodem uses the CPU internal DAC 1 on CPU pin PA4. The board connector is located next to the voltage regulator chip and is labled "Modem" on the AQ32 V2 board.
The softmodem is enabled in UserConfiguration line 167 by uncommenting
//#define SoftModem // Enable usage of DAC as modem on AQ32 instead of Serial 2
Serial 2 can be used for other tasks."_

**Comment by fiam** [comment]
@OpticalNZ I've been looking at exactly this feature recently. The problem is that the DAC pins are not arbitrary. You need to use either PA4 or PA5 (or both for stereo applications). In most boards those pins are either already used for something else or not broken out. This means few users would benefit from this feature.

Note that you can already connect a simple FSK modem to a serial port and then pipe its output to the audio signal.

**Comment by fiam** [comment]
@OpticalNZ You can find how to build such a modem here https://www.rcgroups.com/forums/showthread.php?2963807-FSK-Modem-in-RC-Obsolete-or-a-hidden-gem

**Comment by wx4cb** [comment]
so question. if you was to use a DDS oscillator you would only need a couple of pins, plus there are those that work on I2C, you wouldn't need to do much coding, just tell it whether it's a high or a low. but there are also FSK modem chips you can use such as AD5700. personally. I use XBEE modules on 900 meg for mine as i'm not using it for long range yet. either way would be fine because of a 433 control link

**Comment by PiManASM** [comment]
Do you need a DAC? Seems like PWM would be fine, with the Arduino FSK Library you can just use digital IO pins

**Comment by Nandox7** [comment]
Don't think a DAC is required since in the past other implementations were not using it.
i.e.: https://github.com/KipK/minoposd_audiomodem

**Comment by fiam** [comment]
@Nandox7 The problem with PWM from any non-DAC pin is that you probably need additional external components to reduce the voltage (PWM will be 3.3V, while audio expects 2.5Vpp) and maybe to smooth the PWM into a sine wave.

To me, it seems like a lot of work for a small return, since those HW FSK modems are small and work quite well (I've built a few myself since this issue was opened). You could make them even smaller by using SMD components.

**Comment by Nandox7** [comment]
I agree, plus you'd need a steady signal and that would assume you still have free timers in the FC.

I do plan to do that, go the HW way potentially as SMD to make it small enough to fit small lightweight sized wings.
