### ISSUE TITLE
Add SOFTSERIAL support for MATEKF405 targets

### ISSUE THREAD

**Issue by digitalentity** [iNavFlight/inav#2426]
Possibly on S5/S6 pins

**Comment by chrishbz** [comment]
@digitalentity This is a great idea for an enhancement! But I would **not** suggest to use S5/S6 but instead other pads for the following reason:
- Matek F405-STD is great for airplane pilots, especially when combined with Matek FCHUB-W when you need 2 motors and 4 servos.
- S6 (PA8) is intended to be used for Rudder (see official document: http://www.mateksys.com/?portfolio=f405-std#tab-id-6 on the right column)
--> therefore S6 as SOFTSERIAL **would break the whole benefit** for this board combined with inav on an airplane.
- RX5/TX5 are one candidate for SOFTSERIAL. Benefit: They are also available on FCHUB-W (see http://www.mateksys.com/?portfolio=fchub-w#tab-id-2 ), therefore RX5/TX5 would give possibility for example for Smartport without any further soldering.
- RX4/TX4 are another candidate for SOFTSERIAL. Benefit: As they are very near to Sbus-Pin. One could use Sbus-Pin for inverted Sbus-Receiver and softserial on TX4 for smartport and the two cables stay together very near to each other.
- S5 is one candidate for SOFTSERIAL TX-only. Benefit: Why would personally I need SOFTSERIAL? Because on F4 I have no inverters for smartport. If I am right, in any case the only need for SOFTSERIAL on this FC ist because I need one inverted TX. Because there is no other need for S5 (instead for hexacopters) this would be the one pin, that I could resign.

**Comment by digitalentity** [comment]
#2842 merged. Closing
