### ISSUE TITLE
OSD stats won't fit NTSC screen

### ISSUE THREAD

**Issue by krzysztofmatula** [iNavFlight/inav#2574]
For some reason I use NTSC for FPV and the final flight stats won't fit the screen:
<img width="721" alt="zrzut ekranu 2017-12-10 o 18 18 19" src="https://user-images.githubusercontent.com/16244785/33807411-029bdd5e-ddd7-11e7-9ce1-0da1f3705f46.png">

There should be one more line - "DISARMED BY", which is not visible.
Maybe the whole stats could be printed one line up, as there is space on the trop?

It would be also nice to have odometer stats on this screen (total flight time and total distance), but how to fit them?

**Comment by shellixyz** [comment]
This could be because of the settings of your DVR. With the Eachine ProDVR I need to select the DL option to see all the lines of the OSD. The goggles can crop the image also. Is it the same in your goggles ? But yes the stats could probably be moved one line up.

Aren't total flight time and total distance already on this screen (traveled distance and fly time) ?

**Comment by krzysztofmatula** [comment]
By odometer stats I mean `stats_total_time` and `stats_total_dist` (cumulative stats, not the last flight).

**Comment by digitalentity** [comment]
Fix merged. Closing
