### ISSUE TITLE
LED_STRIP lock up on F4 compiled with GCC 7

### ISSUE THREAD

**Issue by stronnag** [iNavFlight/inav#2782]
Continuation of #2372.

It has now been demonstrated that F4 hex for at least Matek F405OSD and Omnibus F4 Pro V3 that enabling LED_STRIP causes the board to lock up during initialisation (verified with gcc 7.2 and 7.3). Hex compiled with gcc 6.x are not affected.

**Comment by digitalentity** [comment]
This is a real pity. Any idea what might be causing this?

**Comment by digitalentity** [comment]
I'm going to have a crack at this bug. I have a gut feeling that it might be a buffer overflow issue yet again.

**Comment by digitalentity** [comment]
Nailed it. Hardfault was caused by division by zero in ledstrip code. For some reason the same code didn't yield a hardfault exception under GCC 6 and earlier.

Interestingly `DIV_0_TRP` exception is masked in both cases, so division by zero should yield zero result and not generate a fault. Maybe analyzing assembly listing may provide some insight but I'm too lazy to do it 😄

**Comment by stronnag** [comment]
good job. Always satisfying nailing this sort of problem.

**Comment by digitalentity** [comment]
And always amazingly hard to track.

**Comment by digitalentity** [comment]
Fix merged.
