### ISSUE TITLE
Starnge behavior when activating MSP on Matek F722

### ISSUE THREAD

**Issue by Antiheld86** [iNavFlight/inav#2963]
### Board and Version
Matek F722-STD
# version
# INAV/MATEKF722 1.9.0 Mar 18 2018 / 17:09:41 (dc4ef594)

Custom Hex from #2922 
https://github.com/iNavFlight/inav/files/1822880/inav_1.9.0_MATEKF722.hex.zip

### Behavior
When activating MSP on UART4 motors react strange. Motor 1 and 3 work normal. Motors 2 and 4 don't spin up at first, but when motors 1 and 3 spin up to max and then down again motors 2 and 4 give full throttle and don't stop till battery disconnect. Even disarm won't stop them.

Did not try the other UARTs because other rhings are connected. Wanted to connect ESP8266 Wifi module on UART4 via MSP.

**Comment by shellixyz** [comment]
Might be fixed in the development branch. Could you please try with this hex. Just remember if you try to fly with this hex that it is from the development branch and not as well tested as releases you might have other issues with it.

[inav_1.9.1_MATEKF722.hex.zip](https://github.com/iNavFlight/inav/files/1843342/inav_1.9.1_MATEKF722.hex.zip)

**Comment by Antiheld86** [comment]
Its working correctly. Thank you!

**Comment by shellixyz** [comment]
Good to know thanks for testing
