### ISSUE TITLE
Board Revo frsky telemetry

### ISSUE THREAD

**Issue by albebert** [iNavFlight/inav#3014]
Hello

on a CC3D REVO board i can't get frsky telemetry working.

several configuration tested. UART 1 (with inverter), soft serial.  reverse telem ON/OFF

inverter on uart1 is working because is i use it for sbus input it work great. 

thanks for help

**Comment by shellixyz** [comment]
You can't use the SBUS inverter for telemetry because SBUS is unidirectional while S.Port is bidirectional and also the inverter is only connected to the RX line of the UART. To use S.Port telemetry with a soft serial port you need `telemetry_inversion` set to `ON`. If you want to use S.Port telemetry on an UART using the Revo board (or any other F4 without telemetry pad/inverter) you need to build an [inverter](https://quadmeup.com/smartport-inverter-for-f4-flight-controllers/) or get the uninverted S.Port signal from your receiver. More details on how to achieve that here: https://oscarliang.com/uninverted-sbus-smart-port-frsky-receivers/

**Comment by albebert** [comment]
ok, so on soft serial with telemetry inversion normaly it's working ?

**Comment by shellixyz** [comment]
It should work yes

**Comment by albebert** [comment]
ok so tested : 
soft serial activated,
uart 6 as smartport

 get telemetry_inversion
telemetry_inversion = ON

but no telemetry :(

telemetry is working, because i've RSSI and rx input voltage, and if i plug a frsky lipo sensor i see it.

**Comment by shellixyz** [comment]
There is no softserial pins defined for the REVO target. You can't just use any hardware UART as a softserial port. If you want to use softserial you need to define the pins to use for the softserial port and make a custom build.
