### ISSUE TITLE
MSP difference from cleanflight/betaflight

### ISSUE THREAD

**Issue by humanoid2050** [iNavFlight/inav#3088]
inav/src/main/msp/msp_protocol.h lines 234 and 235 have definitions for 

```
#define MSP_SPECIAL_PARAMETERS          98 // Temporary betaflight parameters before cleanup and keep CF compatibility
#define MSP_SET_SPECIAL_PARAMETERS      99 // Temporary betaflight parameters before cleanup and keep CF compatibility
```

Cleanflight/betaflight have changed these IDs to 
```
#define MSP_CAMERA_CONTROL              98
#define MSP_SET_ARMING_DISABLED         99
```

There is no FC code to handle these IDs, so there is no impact at this time. Just an FYI.

**Comment by humanoid2050** [comment]
There is another difference in the definitions for `MSP_VOLTAGE_METER_CONFIG`, `MSP_SET_VOLTAGE_METER_CONFIG`, `MSP_CURRENT_METER_CONFIG`, and `MSP_SET_CURRENT_METER_CONFIG` messages.

For example, the cleanflight/betaflight define the `MSP_VOLTAGE_METER_CONFIG` message as follows

```
case MSP_VOLTAGE_METER_CONFIG:
        // by using a sensor type and a sub-frame length it's possible to configure any type of voltage meter,
        // e.g. an i2c/spi/can sensor or any sensor not built directly into the FC such as ESC/RX/SPort/SBus that has
        // different configuration requirements.
        BUILD_BUG_ON(VOLTAGE_SENSOR_ADC_VBAT != 0); // VOLTAGE_SENSOR_ADC_VBAT should be the first index,
        sbufWriteU8(dst, MAX_VOLTAGE_SENSOR_ADC); // voltage meters in payload
        for (int i = VOLTAGE_SENSOR_ADC_VBAT; i < MAX_VOLTAGE_SENSOR_ADC; i++) {
            const uint8_t adcSensorSubframeLength = 1 + 1 + 1 + 1 + 1; // length of id, type, vbatscale, vbatresdivval, vbatresdivmultipler, in bytes
            sbufWriteU8(dst, adcSensorSubframeLength); // ADC sensor sub-frame length

            sbufWriteU8(dst, voltageMeterADCtoIDMap[i]); // id of the sensor
            sbufWriteU8(dst, VOLTAGE_SENSOR_TYPE_ADC_RESISTOR_DIVIDER); // indicate the type of sensor that the next part of the payload is for

            sbufWriteU8(dst, voltageSensorADCConfig(i)->vbatscale);
            sbufWriteU8(dst, voltageSensorADCConfig(i)->vbatresdivval);
            sbufWriteU8(dst, voltageSensorADCConfig(i)->vbatresdivmultiplier);
        }
        // if we had any other voltage sensors, this is where we would output any needed configuration
break;
```

I'm working on a library to interface with the various MSP flight controllers, and this one is a bit of a problem.

**Comment by humanoid2050** [comment]
Found another. `MSP_ARMING_CONFIG` and `MSP_SET_ARMING_CONFIG` have a third field in the other versions.

From betaflight:
```
case MSP_ARMING_CONFIG:
        sbufWriteU8(dst, armingConfig()->auto_disarm_delay);
        sbufWriteU8(dst, 0);
        sbufWriteU8(dst, imuConfig()->small_angle);
break;
```

**Comment by humanoid2050** [comment]
Looks like `MSP_BF_BUILD_INFO` has been fully deprecated in Betaflight, and its functions are covered by `MSP_BUILD_INFO`

**Comment by humanoid2050** [comment]
I'm seeing a number of differences in the response to `MSP_DATAFLASH_READ` messages. The simplest query with only an address (defaulting to a read size of 128) should return equivalent messages. However, supplying a read size will result in different behavior. BF/CF will encode additional fields related to actual read length and data compression that may or may not be present.

**Comment by humanoid2050** [comment]
It looks like the `MSP_OSD_CONFIG` and `MSP_SET_OSD_CONFIG` messages have also diverged to the point where they are not byte compatible anymore.

**Comment by humanoid2050** [comment]
Messages `MSP_ADVANCED_CONFIG`and `MSP_SET_ADVANCED_CONFIG` have a slight incompatibility. BF/CF have no `servoPwmRate` and instead have a DShot related `digitalIdleOffsetValue` parameter in its place. BF/CF has also added a `motorPwmInversion` parameter, but that isn't an incompatibility.

**Comment by digitalentity** [comment]
We are not aiming towards 100% compatibility but it's a nice thing to have.

Regarding `MSP_VOLTAGE_METER_CONFIG` et al - if you see a way of unifying message format - please submit relevant PRs and we'll discuss the proposed change.

Regarding `MSP_DATAFLASH_READ`. Since we don't implement compression, I see no point in clogging the link with additional useless byte. Once we implement compression (if ever), we'll rethink the format.

Regarding `MSP_OSD_CONFIG`. It will probably become deprecated after we merge #2955

**Comment by digitalentity** [comment]
Summoning @DzikuVx @shellixyz @stronnag and @fiam to the discussion 😄

**Comment by humanoid2050** [comment]
I definitely see that not every difference is meaningful to iNav directly. I just figured that since I'm going through all these things, I might as well document them so that i'm not the only person who knows.

**Comment by digitalentity** [comment]
@humanoid2050 hep, having some documentation on MSP messages is great. Having a unified MSP library is even better especially if it's available under some permissive library like MPL or MIT/BSD.

Regarding the MSP message format - some alignment between BF/INAV is benificial, but it's not a top priority given the limited number of developers. If you can submit PRs to INAV and INAV-Configurator to align them better between INAV and BF - it will be much apprecieted.

**Comment by humanoid2050** [comment]
The particular project i'm working on is a stand alone library to communicate with a flight controller using MSP. So far it looks like most message versions can be accommodated, but I occasionally have to add extra fields to indicate if a particular field (or group of fields) was decoded or should be encoded. There may also be a couple messages that communicate with different units for the same fields. Still looking into that. Otherwise the ones listed here are the ones I've found so far that are truly byte-incompatible.

**Comment by humanoid2050** [comment]
The messages `MSP_RC_TUNING` and `MSP_SET_RC_TUNING` have also diverged. 

Example from BF/CF:
```
case MSP_RC_TUNING:
        sbufWriteU8(dst, currentControlRateProfile->rcRates[FD_ROLL]);
        sbufWriteU8(dst, currentControlRateProfile->rcExpo[FD_ROLL]);
        for (int i = 0 ; i < 3; i++) {
            sbufWriteU8(dst, currentControlRateProfile->rates[i]); // R,P,Y see flight_dynamics_index_t
        }
        sbufWriteU8(dst, currentControlRateProfile->dynThrPID);
        sbufWriteU8(dst, currentControlRateProfile->thrMid8);
        sbufWriteU8(dst, currentControlRateProfile->thrExpo8);
        sbufWriteU16(dst, currentControlRateProfile->tpa_breakpoint);
        sbufWriteU8(dst, currentControlRateProfile->rcExpo[FD_YAW]);
        sbufWriteU8(dst, currentControlRateProfile->rcRates[FD_YAW]);
        sbufWriteU8(dst, currentControlRateProfile->rcRates[FD_PITCH]);
        sbufWriteU8(dst, currentControlRateProfile->rcExpo[FD_PITCH]);
break;
```

There are a lot of similarities, but the BF/CF version is more representative of a complete system state.

**Comment by DzikuVx** [comment]
My point of view. INAV and BF/CF are independent systems, they only share the same ancestor and some of the features. You can not expect them to be compatible on MSP protocol.
At one point of history we wanted to reuse some of new MSP frames introduced by BF that on the longer run that proven, from my perspective, to make more harm than good on the longer run.

Different features, different setting, different developers. Even when we adopted some of the frames but someone on the BF (for example) side changed anything over there, we had no way to know about it.

@humanoid2050 have you seen https://github.com/iNavFlight/inav/wiki/INAV-MSP-frames-changelog ? 

Our current approach is to add new frames as part of MSP2 instead of reuse or modify existing ones in MSPv1 range.

I realize this is a mess somehow, but this will not change and we will never have the same protocol for all firmwares I'm affraid.

**Comment by DzikuVx** [comment]
@humanoid2050 on the topic of `MSP_RC_TUNING` example and the example you posted, this is the system state of BF. BF team made change to this frame comparing to original format. Who should align this frame on INAV side then? We have more examples like this. Either us changing something or someone else changing something. 
Like I said before, those are independent projects and changes are made independently.

**Comment by stronnag** [comment]
I absolutely agree with @DzikuVx. These are independent firmware with a common heritage.

@humanoid2050 , this is a commendable endeavour, but it's probably better placed as a wiki article than an issue.

**Comment by humanoid2050** [comment]
@DzikuVx @digitalentity @stronnag 

Thanks for the input. I was definitely operating under the assumption that MSP compatibility was a goal. It would certainly make my projects easier. However I do understand that such a goal doesn't directly help iNav. 

So let me ask this to gauge how independent the projects are willing to be. If I went through and stripped out all of the MSP fields that are hard coded to 0 or skipped over because they are unused, would that be considered an improvement? Not promising anything, just making sure I'm on the same page.

**Comment by DzikuVx** [comment]
@humanoid2050 then you would break compatibility with all existing clients. You reorder, remove bytes and existing clients that use those frames are botched. Please remember, that some of those frames originate in MultiWii times.

**Comment by humanoid2050** [comment]
True. That was kind of my point though. If iNav is going to be it's own thing, why not make it truly it's own thing. How many iNav MSP clients are there?

**Comment by DzikuVx** [comment]
INAV Configurator, ez-gui, INAV Mission Planner, mwptools. Those are the ones I'm aware of. Others? Probably few

**Comment by humanoid2050** [comment]
Hmmm. Good point.

**Comment by stronnag** [comment]
On April 23, 2018 3:41:46 PM UTC, "Paweł Spychalski" <notifications@github.com> wrote:
>INAV Configurator, ez-gui, INAV Mission Planner, mwptools. Those are
>the ones I'm aware of. Others? Probably few
>
>-- 
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/iNavFlight/inav/issues/3088#issuecomment-383621597

And a few OSDs (off board) that use MSP and have one setting for both MW and iNav.

**Comment by DzikuVx** [comment]
Truth is, those firmwares are compatible only is a way that they share MSP protocol. But even that is not 100% true since BF did not adopted MSPv2 athough @fiam or @digitalentity published even a PR for that.
And remember there is also Butterflight, Triflight and others.

**Comment by humanoid2050** [comment]
So now I'm a little confused. It seems we just went from inav is it's own thing and we don't need to be compatible to MSP compatibility across product lines is important. 

I can see both arguments, but right now things seem to be in a "mostly compatible" state. As a potential new MSP client, that's probably the most annoying condition for me.

**Comment by DzikuVx** [comment]
to make things worse, please remember that MSP is originally for MultiWii. Then someone made nasty hacks in Baseflight, than Cleanflight, then Beta and INAV in parallel, then CF resetted to Beta....There are multiple projects involved and this is not homogenous environment. The way I see it, only MultiWii is really compatible with MSP. After all, MSP stands for MultiwiiSerialProtocol

**Comment by stronnag** [comment]
The differences are well understood and one thing that is guaranteed to upset the authors of existing products (that currently work with MultiWii, iNav, βF --- because the authors understand the extant differences) would be to break the current API.

A number of us (myself, Bart (ezgui) fought this battle a long time ago when we tried to persuade Alex  and Dominic to rationalise MSP across MW and CF. Which came to nothing and we have the mess that we have now.

Forcing existing applications to support yet another variation of MSP just means there will be fewer third party applications.

**Comment by digitalentity** [comment]
@humanoid2050 It's not possible to align certain APIs between Multiwii/INAV/Betaflight/Whateverflight because these projects seek different goals and add different parameters. 

I.e. `MSP_RC_TUNING` message: INAV doesn't have the concept of `rcRates`, we removed it quite a while ago and kept the message compatible by keeping first byte to 100 (was `rcRate`). Since then Betaflight not only kept `rcRate`, but extended it to be a per-axis concept. INAV, however, recently introduced specialized rates for manual control and exposed a new message `MSP2_INAV_RATE_PROFILE`. 

Similarly for `MSP_ADVANCED_CONFIG` and other incompatible messages - different firmware add different parameters. 

To keep things ultimately compatible **all** firmwares will have to add **all** parameters regardless of usability. A goal next to impossible to acheive. Also (and @stronnag is right about this), currently MSP clients are aware of differencies and use different message formarts to talk to different firmwares. Suddenly adding a "unified" MSP protocol will add another implementation to maintain. **Another** - because of a requirement to stay compatible with existing non-unified MSP firmwares.

**Comment by humanoid2050** [comment]
So uniformity is impossible and yet no one is willing to be different.

**Comment by digitalentity** [comment]
INAV started to diverge from the flock by introducing MSPv2 and adding new message frames only to MSPv2 commands keeping legacy MSPv1 binary compatible or deprecating them. However other firmwares don't follow the same path and keep reshaping MSPv1 commands to meet their requirements.

**Comment by humanoid2050** [comment]
In that case I will proceed under the assumption that nobody cares enough one way or the other to try to unify or to do an iNav specific code cleanup (knowing that iNav-friendly programs would have to undergo a similar cleanup).
