### ISSUE TITLE
New feature request: OSD navigation menu improvement, waypoint tools

### ISSUE THREAD

**Issue by Troyhy** [iNavFlight/inav#3129]
Navigation menu in OSD should have an option to load mission from eeprom. This would be useful in situations where mission loading is not possible in the field situation.
In addition basic info about loaded mission in FC memory would be really useful way to verify mission before flight.

This could be implemented on own submenu under navigation. For example MISSION or WAYPOINTS

Menu suggestion:
```
> Load EEPROM mission
  -----
  Waypoints:       10
  Return to home:  True
  Landing:         False 
```

**Comment by digitalentity** [comment]
Loading a mission from EEPROM is possible with sticks combo for a while now, but I agree, having an OSD menu for this might be a good idea. @fiam @DzikuVx ?

**Comment by Troyhy** [comment]
I still think this would be good idea to implement...

**Comment by tonyyng** [comment]
> Loading a mission from EEPROM is possible with sticks combo for a while now, but I agree, having an OSD menu for this might be a good idea. @fiam @DzikuVx ?

I'm not sure whether replying to this issue is the right approach, but I've made some changes in my personal (disconnected) repo related to mission loading and OSD info and test flown them.  I'd like to get some feedback before going through the effort to merge the work and create a pull request.  How can I get some discussion on the way I've done things?

**Comment by Jetrell** [comment]
I was thinking of opening a new feature request concerning this matter.

@digitalentity @tonyyng @breadoven 
Is there any reason why iNav can not be set to detect a loaded waypoint mission in the eeprom when a GPS lock is attained. 
Then automatically load the mission to the FC from the eeprom. Without the need for OSD stick menu loading.
I often forget to load the mission to the FC, because other software I use doesn't require this step.

What do you guys think?

**Comment by tonyyng** [comment]
I've already added this as a pull request: https://github.com/iNavFlight/inav/pull/6612

**Comment by Jetrell** [comment]
> 
> 
> I've already added this as a pull request: #6612

I'd totally forgot about reading that. Awesome work :+1:

**Comment by breadoven** [comment]
Yes there are various mission related PRs adding useful functionality or even bug fixes that are currently loitering in the system.

I've used parts of https://github.com/iNavFlight/inav/pull/6612 without bothering with the setting so it always loads a mission if it exists. If it causes problems (first WP too far) or you want to unload it anyway just use the stick command. Bit of a no brainer really that avoids unnecessary landings.
