### ISSUE TITLE
Deprecate mid_rc setting

### ISSUE THREAD

**Issue by digitalentity** [iNavFlight/inav#3313]
Since all FC code expects RC channels to be in [1000;2000] range and we have `rxrange` to scale the inputs - we don't really need `midrc` as a setting. A hardcoded `PWM_RANGE_MID` define would suffice.
Related to #3312

**Comment by DzikuVx** [comment]
Fine by me

**Comment by NeilGaede** [comment]
Great. That sucks. Now back to ground zero on the altitude hold problem. If I use mid_thr (expo mid) for my alt_hold and I have mid_thr at zero so my expo is right, then the copter gains altitude and fights the alt_hold when I try to make corrections. If I change the code to use mid_rc and rcdata[throttle] instead of rccommand then it works perfectly. Altitude hold center value needs to be referenced to middle stick position, not expo center weight value.

**Comment by teckel12** [comment]
@digitalentity See #3309

**Comment by digitalentity** [comment]
My point is that having a different neutral point for throttle expo and
zero climb rate is unreasonable. For that specific bug expo code should be
fixed, not a hack that will fix just althold case.

**Comment by fiam** [comment]
Completed with the merging of https://github.com/iNavFlight/inav-configurator/pull/484
