### ISSUE TITLE
Nav launch not correcting itself

### ISSUE THREAD

**Issue by Cutbangrian** [iNavFlight/inav#3383]
Hi, I'm ryan. I'm using Inav Version 1.9.3 on my versa wing (flite test model) with Omnibus F4 pro V2 board.
Currently, I just saw this video https://www.youtube.com/watch?v=YEqkvjQeu0Q while looking up for another inav user experiences.

Later on, I try to launch my versa wing like he did on the video. or in another word, swing it.
oh ya I forgot to mention that I dont have blackbox record and all setting goes default as on inav wiki fixed wing guide.
and this is not my first launch. I've use manual mode for the first time and use servo auto trim and also tuning piff. all features RTH, failsafe, althold, poshold is working perfectly.

Since I watched that video, I want to try the last feature that I havent try. Nav launch.
- switch to nav launch mode, switch to arm, adjust throttle 50 % and throw it.

when I throw, I mean by swing it up just like in the video, 
as I released the model, the motor start to spin up.
 BUT the model just not correcting it self and ended with banking left then dive to the ground very hard.

what wrong? I thought Inav 1.6 or later could use autotune piff without worrying to input the value manually.
I read the wiki to throw the model in straight and level in nav launch mode.
but what should I do if I want my model to react faster and correcting it self just like in the video?
what value that Ive to change in the CLI?

anyone please help. its so appreciated. thanks

**Comment by giacomo892** [comment]
That video is just an example on how **not** to launch a wing.. It does the magic to stay airborne just because it is overpowered and perhaps it has crazy high level PID P.

Just be sure to toss the wing sightly with the nose pointing upwards and give it a gentle throw. Autolaunch will take care of the rest but it will not do magics. Be sure to throw the wing into the wing, if any, it will help **a lot**! 
If you still have difficulties you can make the prop already spinning before the launch with `nav_fw_launch_idle_thr` setting it to a value where you feel the prop already producing some thrust and lower the `nav_fw_launch_motor_delay`to something line 200 to make the motor starting pushing earlier than stock settings.

**Comment by Cutbangrian** [comment]
Great... thanks!

But as you say that he got crazy number on P value,
It should be doing something like overcorrect or oscillate right?
But it doesnt.

It fly straight and perfectly

**Comment by shellixyz** [comment]
It probably just that his wing is overpowered, very agile and well tuned. As you said crazy high P would lead to oscillations.
