### ISSUE TITLE
Add support for tbeacon gps output

### ISSUE THREAD

**Issue by JonnyFPV** [iNavFlight/inav#3435]
Hello, 

If it’s possible please add support for tbeacon 

Found here https://tbeacon.org/?page=20&language=en

It can read gps coordinates and speak it back over uhf :)

**Comment by flounderscore** [comment]
Doesn't tbeacon just need to be connected to the GPS signal in parallel to the FC (GPS TX)?

**Comment by wx4cb** [comment]
you need to be careful of parallelling serial ports between more than 2 devices because the open drain lines of one my drag down the other lines to the other device.

I would suggest just paralleling off the transmit line of the gps to the two devices and use the FC to configure the gps module itself.

this is exactly what they recommend in the documentation: https://tbeacon.org/?page=13&language=en

**Comment by shellixyz** [comment]
@JonnyFPV As @flounderscore and @wx4cb stated you only need to split the TX line from the GPS and connect it to the RX line of the tBeacon (don't forget the ground line too obviously). No support in iNav needed.
