### ISSUE TITLE
SmartAudio not working with FF_PIKOF4OSD and AKK Nano2 VTX

### ISSUE THREAD

**Issue by flounderscore** [iNavFlight/inav#3437]
I tried to use SmartAudio with the latest Development version and a AKK Nano2 VTX. I checked the pin and there is some signal. Previously, the same VTX was working on betaflight 3.4rc2 and a CLRACINGF4 nano.

It seems there was (is?) some incompatibility with AKK VTXs looking at some of the betaflight issues. Any suggestions what I could try?

**Comment by fiam** [comment]
@flounderscore Does it work with normal Betaflight or does it need the special AKK branch? I've tested the current implementation with an AKK X2 and it's working fine.

If your VTX needs the SmartAudio hacks in order to work, I'm willing to merge them if someone provides PR with a setting to enable/disable the workaround.

**Comment by flounderscore** [comment]
I start to suspect a hardware problem. The FC correctly sends requests but not reply from the VTX.

During setup I did connect smart audio once without powering the VTX. Maybe that shot the logic inputs (although one would hope that there is some sort of series resistor on the VTX...). Other than that the VTX is working and I'll use it for now. If I have time I'll try the VTX with another FC that worked before, but if it ain't (totally) broken...

Should I close the issue for now?
