### ISSUE TITLE
2.0-RC1 - LTM telemetry not working on OMNIBUSF4V3 UART6

### ISSUE THREAD

**Issue by krzysztofmatula** [iNavFlight/inav#3466]
Steps to reproduce:
- flash 2.0.0 with full chip erase
- configure UART6 for LTM:
```
# diff
# INAV/OMNIBUSF4V3 2.0.0 Jun 26 2018 / 22:55:06 (9ebdb8317)
feature TELEMETRY
serial 5 16 115200 38400 57600 115200
```
- check that telemetry is not working, while it should...

Also by using SOFTSERIAL1 (which share UART6 TX pin) telemetry is not working...

**Comment by krzysztofmatula** [comment]
@digitalentity, it stopped working from this commit:
```
commit 9e6e2b3f6506aef5e5ed126cf8911cf573c51cdb
Author: Konstantin Sharlaimov <konstantin.sharlaimov@gmail.com>
Date:   Wed May 23 16:44:30 2018 +1000

    Timer driver refactoring (#3120)
    
    * Initial cut on timer cleanup and refactoring
    * Remove unused code
    * Dynamic timer state allocation
    * Remove USABLE_TIMER_CHANNEL_COUNT and USED_TIMERS definitions
```

**Comment by krzysztofmatula** [comment]
Further investigation shown that the telemetry actually outputs from the TX pin, but the UART signal inverted! No mater if I use HW serial or SOFTSERIAL. No matter if I select serialrx inversion or not. Since the mentioned commit this pin output is inverted.

The actual board I use is genuine Airbot OmnibusF4V5. Both RX and TX pins don't go directly to MCU, but to small 8-leg chip labeled "L82". It is suspected that this chip allows for the inversion to be configured on both lines (RX and TX) and configured separately. Then, maybe we just don't setup the pin as needed...

**Comment by digitalentity** [comment]
Actually, prior ot 2.0 your setup worked by exploiting a bug in timer initialization code:

Here's how it worked before:
1) System boots. All GPIOs are initialized as floating with weak pull-ups
2) Timer init code goes through `timerHardware[]` and initializes all listed timers regardless of being used or not. Timer at reset is initialized to keep it's outout low
3) Further code doesn't initialize a timer that uses PC9
4) Invertor is not activated
5) Profit

In 2.0 timer init code changed to touch only timers that are being used:
1) System boots. All GPIOs are initialized as floating with weak pull-ups
2) Timer init code enables clock of all timers listed at timerHardware[]
3) Further code initializes all timers that are actually used
4) PC9 stays initialized as floating+weak pullup, inverter happily inverts the signal
5) UART6_TX is inverted. WTF?!?

I don't think we'll fix this in 2.0 since it requires separation of inversion of TX/RX lines where possible.

**Comment by krzysztofmatula** [comment]
![zrzut ekranu 2018-06-30 o 00 32 42](https://user-images.githubusercontent.com/16244785/42128641-8c469cb0-7cb0-11e8-90f1-840f39fcda39.png)

I'll take a look, maybe there's a simple way to configure PC9 pin. 
Target should define there is a separate TX inverter pin and at least it should be then initialized to some default value.

**Comment by krzysztofmatula** [comment]
"LTM telemetry shared with SBUS not working on OMNIBUSF4V3 UART6" - non-shared also didn't work. Any TX on UART6 didn't work, because of TX inverter being driven.
