### ISSUE TITLE
Number SATS on OSD not show MatekSE wing

### ISSUE THREAD

**Issue by Cipotal** [iNavFlight/inav#3521]
New flash Matekwing SE firm. All features function ok. But in OSD not show NUMBER OF SATELITES. Hdop quality is showed good in OSD. 
The osd configuration not function properly, very erratic issues. Osd is transparent.

**Comment by shellixyz** [comment]
What firmware and configurator versions are you using ? Did you update the OSD fonts (Font manager in the OSD tab) ?

**Comment by Cipotal** [comment]
Thx for answer, but finally it appears. While the GPS don't catch 6 sats mínim, the number of sats doesn't appear in the osd. 

End of topic.

**Comment by shellixyz** [comment]
Maybe the hardware OSD blinking doesn't work correctly on your board. Try setting `display_force_sw_blink` to `ON`

**Comment by Cipotal** [comment]
Woow, is the solution. Thanks. Was OFF. 
Yesterday with the old config, the altitude and the battery voltage desapear and re-appear. 
Tomorrow try with the setting ON.

**Comment by teckel12** [comment]
I believe that switch should default to ON not OFF. Going with the higher compatibility option.

**Comment by shellixyz** [comment]
Not sure it is sub-optimal and seems to be needed only for a small number of boards (probably defective OSD chip).

**Comment by teckel12** [comment]
@shellixyz I believe the issue isn't the OSD chip but the goggles.  I have non-Chinese Omnibus F4 Pro boards and I need to set `display_force_sw_blink ` to `ON`.  But, I'm using cheap goggles which I believe is the issue.

I think this issue is more common than reported.  And going with the option that works for everyone seems to be the logical default.  It was always software blink previously and no one had an issue.

Not a huge deal to me as I know the solution.  But we continue to get this issue.

**Comment by shellixyz** [comment]
@teckel12 I really doubt the issue comes from the goggles. I'm using cheap ones EV800 and VRD2 and never had this issue.

>  It was always software blink previously and no one had an issue.

Are you sure about this ?

**Comment by fiam** [comment]
@teckel12 I'm not sure if the problem is in the goggles. Whenever I see a few reports of this problem, they seem clustered around a batch of the same FC rather than the same goggles. Keep in mind that manufacturers of original boards are not immune to receiving a bad batch of MAX7456. Maxim doesn't produce it anymore, so all MAX7456 - even the ones in original FCs - are kinda "clones" of varying quality.

**Comment by teckel12** [comment]
FC or goggles, it still seems the more compatible route would be the best default. And I remember when the hardware blink was added, we immediately started getting reports of missing OSD sensors. Only then was the `display_force_sw_blink` option added to go back to the old software blink method.
