### ISSUE TITLE
Servo Gimbal Feature Removed in 2.0? Flaps Button Resets Itself in Config.

### ISSUE THREAD

**Issue by disposablehero2** [iNavFlight/inav#3602]
Matek F405 Wing 
V2.0 RC3

Hi, Has the servo gimbal feature been removed in 2.0? trying to get a simple manual servo to pan an fpv cam but servo slots 0 & 1 either move the elevator and ailerons instead (I think they are trying to level the cam?). Can't put it on servo slot 6 either as that seems controlled by throttle. Are the servo sslots fixed in terms of function? I read the wiki on how to do manual servo gimbal control but there is no gimbal control feature in either the config or cli that I can see. Also, the "does this craft have flaps?"  in the mixer window doesn't seem to do anything and resets on reboot. Thanks for all your hard work.

**Comment by Tygrys-1** [comment]
You have to go to Mixer tab in the configurator, in Servo Mixer click "Add new mixer rule" then set a "Gimbal Pitch" and "Gimbal Roll" Input to the servo of your choice. 

The "has flaps" switch adds a 2 flaperon mixes on the servo mixing. Once added there is no function of that button, but I think it should enable the "flaperon" mode switch in modes tab. It is the configurator problem and is reported there [Issue 517](https://github.com/iNavFlight/inav-configurator/issues/517)
As a workaround you may use free rc chanel switch instead of "flaps" input, or configure flaperon mix in the transmiter.

**Comment by disposablehero2** [comment]
Thanks, I have landing gear on servo 7 with pwm 8 (gave up on flaps). I tried putting either servo 1 or 0 as rc channel 8 for manually controlling the camera pan servo (and moved all the pwm outputs to suit the re-arranged servo table) and now the cam pan works but the landing gear stopped working! If I remove channel 8 on the Taranis (or the mix in the servo mix - and rearrange all the pwm outputs again) I get the landing gear back. It is like you can either have rc channel 7 OR 8. Not both on the same model. Think I am going with a simple pwm gyro for now lol. Good luck.
