### ISSUE TITLE
GPS always shows last lock coordinates and altitude

### ISSUE THREAD

**Issue by teckel12** [iNavFlight/inav#3603]
Is it the correct behavior that rc4 always shows the last GPS lock coordinates and altitude?  As soon as I plug in, I get my last latitude/longitude/altitude (in my basement where I never get a GPS signal).  It also happens immediately.

Previously, it would output 0/0 for latitude/longitude and for the altitude 0m for v1.9.1 and -17m for v2.0.0.

Maybe it's good that it does this? Not sure yet.  Seems like it's intentional.  It confuses the heck out of me as I assume there's no coordinates till there's a lock.

**Comment by fiam** [comment]
@teckel12 https://github.com/iNavFlight/inav/issues/3545#issuecomment-404258437

**Comment by teckel12** [comment]
@fiam I don't follow the reference. In RC2 it would show lat 0, long 0, altitude -17m before fix. And this was said to be coming directly from the GPS. But in RC4, I get what seems to be the last good GPS fix information as soon as I start up the FC, without a GPS fix.

So is this what's supposed to happen? This means that now it's NOT sending the information directly from the GPS like it was in RC2. Instead (at least it seems) that the last good GPS lock is cached by INAV and that cached value is sent till there's a GPS lock.

I haven't decided if this is a good or bad change, it seems like a good change on the surface. It's just that it's different than RC2 and I'm not sure if it was intentional or not.

**Comment by fiam** [comment]
@teckel12 It's coming from the GPS, which is probably doing the caching itself.

INAV 2.0 sends the GPS information as long as either you have a GPS fix or either you have never armed. This way you can see the sensor as soon as you power up, but if the GPS fails during a flight the radio will emit a "sensor lost" alarm and keep the last known coordinates even without logging enabled.

We made that change because a lot of users were confused by the fact that they needed a GPS fix in order to be able to discover the sensor.

You should look at `FSSP_DATAID_T2` to determine wether there's a fix. I think the format of that sensor hasn't been changed since 1.9.1 AFAIK.

**Comment by teckel12** [comment]
@fiam When I went back to RC2 it went back to lat 0, lon 0, alt - 17m. Something else is going on here...

**Comment by teckel12** [comment]
It seems now I'm confused as a result of making everyone else less confused.  Anyway, my GPS timed out or whatever and now today it's back to lat/lon 0/0 and an alt of -17m with RC3.  I guess it's a good thing to always output the coordinates directly from the GPS receiver.  But different times showing different information confuses the heck out of me.
