### ISSUE TITLE
minimum RSSI value is not displayed correctly

### ISSUE THREAD

**Issue by jaames74** [iNavFlight/inav#3607]
Fresh flashed Inav2.0RC4 on spracingF3, frsky X8R with pwm-to-analog-converter.
X8R rssi is 0-3.3V tested with multimeter. Shows as 32% to 100% in Inav configurator.
Cannot be configured properly with RSSI_SCALE.

Also tested with inav 1.9.1 - same behavior.

**Comment by teckel12** [comment]
Have you tried sending the RSSI back from your transmitter to your FC? I could never get RSSI to work correct directly from receiver to FC.

**Comment by jaames74** [comment]
@teckel12 i don't understand what you are talking about. My radio is very old - Spektrum DX7 with Frsky DHT module. Analog RSSI works OK with other firmwares such as ardupilot or betaflight. Why not with INAV??

**Comment by r3df1v3** [comment]
Same here with a Thomas Scherrer LRS receiver.
If I set the RRSI to read max value at 99%, then when switching off the TX, never goes down more than 75%.
Please, fix that  scale!!
Also, it would be interesting to have an option to activate failsafe if RSSI goes under some low value. Otherwise, how can you cope with a broken RX antenna, or an unplugged PPM cable?

**Comment by fiam** [comment]
Fixed in #3613
