### ISSUE TITLE
In horizon mode, slow to auto level when release stick while exactly inverted

### ISSUE THREAD

**Issue by DaleKramer** [iNavFlight/inav#371]
When I release my transmitter stick in horizon mode, while I am precisely inverted, I have had my craft take 8 seconds or more to return to a level attitude.  

When I release my stick in horizon mode a all other angles, my craft rights itself immediately (~1 second depending how far from level it was)

Is there a way to fix this or at least warn people that when flying precisely inverted, in horizon mode, your craft can be slow to recover when you release the stick (especially of interest to fixed wing craft)?

**Comment by digitalentity** [comment]
@DaleKramer I assume you roll axis is still locked out.
The problem here is that "inverted" state is desribed as 180 deg _roll_ not 180 deg pitch. Therefore, your machine will try to _roll_ into upright position which is impossible to do as your roll axis is locked out.
This effect is due to we use euler angles to control the attitude.

**Comment by DaleKramer** [comment]
Makes sense, yes still only pitch axis free to roam :)

Thanks
