### ISSUE TITLE
[feature request] parameters for mission waypoints (time to stay, action, etc.), numbering waypoints

### ISSUE THREAD

**Issue by Pitichinaccio** [iNavFlight/inav#3890]
Hello,
I had the idea of adding some more parameters to the waypoints of a mission, like time to stay (until flying forward to next WP), actions (staying still, heading to certain direction, turning round with defined speed) and things like that.
There was also an other suggestion on the INAV group at facebook to add numbers to the waypoints and have them dislayed on the OSD.
Unfortunately my programming skills are to poor to do this on my own, but maybe it is an idea worth thinking about. Thanks!
Bernd

**Comment by stronnag** [comment]
See the sadly unloved #154

**Comment by StewLG** [comment]
![waypointdisplaydemo](https://user-images.githubusercontent.com/7128339/47269143-b81d8180-d50e-11e8-8f99-c42d36a0f122.PNG)

I am working on your request to show waypoints and waypoint numbers on the OSD. Unfortunately I am running into performance problems due to the short amount of time allocated to OSD re-draw. 

https://github.com/StewLG/CraftServices
