### ISSUE TITLE
Servo Support on Output 2

### ISSUE THREAD

**Issue by bigb2000** [iNavFlight/inav#4074]
I'm coming from Betaflight and i'm new to planes at all so i bought i omnibus f4 nano v2 board (FIREWORKSV2 target) and just realized that iNav is not capable of remapping resources. This FC has 4 PWM outputs and i need is 2 channels for aileron and one channel for elevator control in addition to the motor output 1. What i understood is that the servos are fixed to outputs 3 to 5 with such a mixer config and so i am unable to use the mentioned board. Output 2 will always be unused when no second motor is in place. Is there a custom build available or would someone of you developer guys be so kind to make a custom build for me with motor 5 mapped to PB1 instead of motor 2 mapped to this signal. Or did i miss some information on how to remap resources?
Thanks to you. I really appreciate your work, which makes my hobby possible.

**Comment by teckel12** [comment]
@bigb2000 You are correct, INAV doesn't have resource remapping nor will it anytime soon due to design priorities. You'll need a custom build. Look at the target source files, it may not be as hard as you think to do yourself.

**Comment by bigb2000** [comment]
Thx. I will try modifying the source and building with the docker image.

**Comment by datamann** [comment]
@bigb2000
You can look at this post on how to use docker if you need to
#3896

**Comment by bigb2000** [comment]
@datamann Thanx. I'm not sure if i made it but changed the line:
   DEF_TIM(TIM3, CH4, PB1, TIM_USE_MC_MOTOR | TIM_USE_FW_MOTOR,   1), // S2_OUT
to
    DEF_TIM(TIM3, CH4, PB1, TIM_USE_MC_MOTOR | TIM_USE_FW_SERVO,   1), // S2_OUT
 
in target.c; built and flashed. and now i can assign 3 servos to outputs 2 to 4. Cannot test on hardware this week but i think i made a step ahead :-)

**Comment by shellixyz** [comment]
@bigb2000 That's right. Just remember that now since you have a servo output using the same timer as a motor output you can only use the same PWM frequency for both servos and the motor. So if your servos only support 50Hz PWM you need to set the motor proto/freq to PWM 50Hz. Otherwise you risk burning your servos.

**Comment by bigb2000** [comment]
Thanks, while you answered i sat in the basement measuring the outputs with an oscilloscope and as you said, the PWM is at 50Hz and cannot be mixed, which i think is no problem for the ESCs. On this board also Output 4 uses this timer so that mentioned problem should have been also before i modified the code in my understanding. Great what i learned today and thanks for all your fast responses. I'm looking forward to see more inside the code. Cheers from beautiful Austria!

**Comment by shellixyz** [comment]
50Hz should be fine. Happy flying. Cheers !

**Comment by doughadfield** [comment]
Hi, I notice this issue is now closed, as the creator now has a custom build which works for him. However this is an issue for me too (and, I suspect, everyone who uses flight controllers with limited servo outputs). Most planes have one motor (some of mine are twin, but I often use the same servo channel for both ESCs, if I'm not using differential thrust). I see that in the mixer presets drop-down in Configurator, there are separate presets for "Airplane" and "Airplane with differential thrust" - currently these seem identical! Surely the sensible configuration would be to have a single motor (and servo mappings starting at S2) for the "Airplane" setting, with "Differential Thrust" setting dedicating S1 and S2 to motors, as at present. Would it be possible to add this fix to the development schedule?

**Comment by mreitschuster** [comment]
Hi any chance this is taken up? I want a mini 1s build and all FCs that I find have only 4 PWMs -> having more than 2 servos would be great.
