### ISSUE TITLE
Looking for fc that is not Omnibus V6

### ISSUE THREAD

**Issue by tehawk** [iNavFlight/inav#4238]
Hello,

Please let me know which FC would be most painless for the following:

4in1 ESC Racerstar Aniversary Edition 35A
BN-880
FS-IA6B

I had Omnibus F4 AIO V6, got it cause it was supposed to be supported, but it was not. Eventually I burned it after connecting battery and I want to avoid it. If you ask me this fc cannot work with VBAT, also it says that it uses target Fireworks V2 but that is not true either.

**Comment by teckel12** [comment]
@tehawk I'm suggesting the Matek F722SE for new builds. More IO ports, fully supported by INAV, fast, rock-solid, future-thinking (ready for blheli_32 telemetry for example), etc. And since the F7 supports unverted UARTS, even tricky FrSky builds with different protocols (for example F.Port) are supported.

I've been very happy with it and probably will use it for future builds till something drastically better comes out.

**Comment by tehawk** [comment]
Thank you very much for suggestion.

I have battery connected with 4in1 ESC, what would be the best way to power fc, from 4in1esc socket VBAT and GRD to + and - designed for battery wires, or directly from + and - pads on 4in1 ESC to + and - pads on fc.

On my previous fc, ibus was connected to RX3 is the same with this fc ?

Is this picture ok ?

![1](https://user-images.githubusercontent.com/46408793/51630973-b4edc380-1f4b-11e9-9e23-d52e174e91de.png)

At the other side of fc there are G, S1-4, do I need to connect this ground even thought I get power from 4in1 ESC?

**Comment by teckel12** [comment]
@tehawk I don't use 4 in 1 ESCs for 30mm builds so I'm not sure. The F722SE is designed for 4 individual ESCs, which is my preferred method to avoid interference.
