### ISSUE TITLE
autoconnect doesn't work on F405-ctr

### ISSUE THREAD

**Issue by laurentopia** [iNavFlight/inav#4340]
clicking on the connect button works though

**Comment by teckel12** [comment]
@laurentopia That would be a configurator issue, not INAV. Please open an issue in that repo. But for what it's worth, I've found this feature hit or miss on many flight controllers and in Betaflight and INAV. And really, it's just as easy to click connect when you want to.

**Comment by laurentopia** [comment]
Yes it is minor. I didn't know it was common to FC, is this a hardware side glitch?

**Comment by teckel12** [comment]
@laurentopia Not sure, probably a glitchy timing thing. Like some FC, ports or drivers take a bit longer than expected. Still, this issue should be on the configurator repo, not here.

**Comment by DzikuVx** [comment]
Please do not use Autoconnect on configurator. It will not correcly work with F4/F7 boards using VCP USB connection. The fact that port appeared in the list does not mean board booted up and is ready so serve requests. Autoconnect will be probably removed since reconnect was fixed and configurator correctly reconnects to FC after reboot

**Comment by laurentopia** [comment]
Great to hear you're removing busted features.
