### ISSUE TITLE
Matek f722 wing current sensor giving bad values

### ISSUE THREAD

**Issue by benjinne** [iNavFlight/inav#4392]
## Current Behavior/Steps to Reproduce
At the default scale (250) and zero offset, the reading is acceptable at idle, then when increasing the current to 1 amp using a clamp meter, inav reports about 1 amp. Increasing till the clamp meter reads 2 amps, inav reports about 15amps, also the values are changing significantly (.5A to 2A) when no changes in throttle are present, and the current meter doesn't show changing current. By increasing the scale, the current doesn't increase as rapidly, however the scale had to be adjusted to 6000 which seems really large to me. Also when I increased the current consumption to 5 amps (reading from amp meter), inav reported 1.7 amps. It seemed like some sort of overflow occurred and the reading went back down, or something is really wrong with the current sensor. 

I also made sure the current_meter_type was set to ADC

## Expected behavior
Should be able calibrate the current sensor to give reasonable values

## Additional context

cli dump:
https://pastebin.com/mJqkT8XD

- FC Board name and vendor: F722 Wing Matek
- INAV version string: INAV/MATEKF722SE 2.1.0 Feb 10 2019 / 16:42:36 (0d3d0ff30)

**Comment by benjinne** [comment]
Has anyone successfully calibrated their current sensor on the f722 matek wing FC? I want to know if mine is defective or if there's actually something wrong in the firmware.

**Comment by shellixyz** [comment]
I should be able to test soon

**Comment by teckel12** [comment]
@benjinne I have the Matek F722SE (same target as the F722 Wing) so I assume the hardware is almost identical.  And I've calibrated my current sensor without issue.  My settings are as follows:

```
set current_meter_scale = 179
set current_meter_offset = 290
```

I calibrate on the bench with props on (quad strapped to cinder block) and use an inline current meter.

**Comment by ShawnzAZ** [comment]
From Matek's site:  http://www.mateksys.com/?portfolio=f722-wing#tab-id-2

Battery Voltage Sensor: 1:10 (Scale 1100)
Current Senor: 132A,  3.3V ADC,  Scale 250

**Comment by teckel12** [comment]
@ShawnzAZ I never look at manufacturer's current sensor values, they seem to never be right. I calibrate on my own, and they're sometimes FAR off.

**Comment by MATEKSYS** [comment]
@teckel12  F722WING has different components and scale of current sense from F722SE
maybe some manufacturers don't know how to count the current scale,  but we always mark right scale according to the components spec in theory.  a bit error is normal due to components value precision.

@benjinne Try old firmware version. http://www.mateksys.com/Downloads/FW/inav_2.1.0_MATEKF722SE_NOV20.hex  from de_pinio branch Nov.20
CLI "defaults" after reflashing

**Comment by benjinne** [comment]
Ok so I tried that firmware, but it seems like I have the same issue still. At a scale of 1500, I'm getting resonable readings from 1-5 amps, however the values are very inconsistent, It'll vary +- 1 amp. I'm not sure what's wrong, however I suspect that it could be a noise issue. I'll try adding a capacitor to the esc leads, and report back.

**Comment by benjinne** [comment]
So I added a low esr capacitor to the esc lead, and set the scale to 250. This time, I'm getting reasonable values from 1-7 amps! However, I'm still getting +-0.5 amp readings. Seems like either I have a lot of noise, or the ADC for the current sensor is having trouble. In case anyone is curious, I'm running a flycolor 30A BLS-Pro esc with a 2216 sunnysky and a 10 inch prop. I also added a 1000uF 35v Panasonic cap .

**Comment by benjinne** [comment]
I updated to latest firmware (F722SE RC3), and I had to double the scale to 500. This time, it seems like I'm getting very accurate values and it doesn't seem to varying as much as before. Maybe +-(0.1-0.2 ) Amps

**Comment by teckel12** [comment]
@benjinne Adding the cap is a good idea anyway, so the exercise had multiple good results.

**Comment by benjinne** [comment]
Thanks, anyways I realised I made a mistake. The scale actually turned out to be 260, and not 500. I'm not sure how I got that value, but just wanted to let anyone who might have a similar issue know where I'm at.

**Comment by teckel12** [comment]
@MATEKSYS In this case, for the F722SE in INAV by default it sets CURRENT_METER_SCALE = 179. So, anyone with a F722 Wing will have a bad default current scale. Maybe there should be a unique target if the hardware is even slightly different.

**Comment by digitalentity** [comment]
Let's keep this open. Seems that we need a different target (or board hardware detection) for WING

**Comment by MATEKSYS** [comment]
@digitalentity no need to add variant for F722-WING,  The current scale is available in manual and our webpage.

**Comment by teckel12** [comment]
@MATEKSYS So only the current sensor is different between the SE and Wing models? If so, I tend to agree that's not enough to warrent a different target. It could, however cause some confusion.

**Comment by krzysztofmatula** [comment]
> for the F722SE in INAV by default it sets CURRENT_METER_SCALE = 179

In my F722SE I had to tune the current meter scale from 179 to 218 to get good readings (or maybe I should have set some shift also - don't really care - mAh  calculation is OK :) ).
So, the defaults are to be treated as initial values anyway.

**Comment by digitalentity** [comment]
@MATEKSYS is there any hardware difference between F722 and F722-WING apart from current sensor resistor?

**Comment by MATEKSYS** [comment]
@digitalentity  F722WING has no ICM20602 builtin, It works fine with default MPU6000.
more variants will confuse users

**Comment by Avegawanderer** [comment]
I have similar issue with Matek F722-wing and iNav 2.1.0.  Increasing throttle gives increase of current up to 10amp, further increasing shows current of about 0-5amp, while after-flight osd summary shows 68amp max, which cannot be reached on my setup. Scale is 250 according to Matek, offset is 0. Seems to be some kind of overflow in software. I'll try to do some tests with static load and check it out if the issue is hardware-related or not.

**Comment by wx4cb** [comment]
im not sure about that. @Avegawanderer i was pulling 72 some-odd amps on my new one the other day.

Brand new F722 wing. and those current values are about correct (changed it to the one as per the matek page for the FC) as i know this setup tops out at about 75 amps.

![vlcsnap-2019-03-19-06h10m09s384](https://user-images.githubusercontent.com/1495297/54597803-9a950b00-4a0d-11e9-8fa0-342046e95429.png)
![vlcsnap-2019-03-19-06h08m26s123](https://user-images.githubusercontent.com/1495297/54597807-9c5ece80-4a0d-11e9-9436-b54e336f7669.png)

**Comment by Avegawanderer** [comment]
So I did some tests and I am convinced that this issue is not an iNav bug, but related to Matek board.
Under static load from 0 to 20amps I get stable and correct current readings. I believe, the actual reason for incorrect current readings is the high side current sensor, which possibly is not as tolerant to noise produced by ESC as more common low side sensor, It seems that the problem only arises when there is no low-esr capacitor connected to ESC (or power output from the FC). So I think that if you use an ESC without electrolytic capacitor (like ESCs for racing drones), a low-esr capacitor on power output of the FC is not only a good idea but  a must.
![20190323_202821_2](https://user-images.githubusercontent.com/2843378/54902271-f4a03f80-4ee9-11e9-90d9-52b37fda7bb5.jpg)
Current sensor output (thin red wire)

![50%](https://user-images.githubusercontent.com/2843378/54898532-c3217700-4edd-11e9-99d8-5a73e605e413.png)
Current sensor output, throttle 50%, no capacitor

![75%](https://user-images.githubusercontent.com/2843378/54898537-c74d9480-4edd-11e9-9fe0-477502a12034.png)
Current sensor output, throttle 75%, no capacitor

![100%](https://user-images.githubusercontent.com/2843378/54898540-c9175800-4edd-11e9-83cb-b37d2d4aaa8a.png)
Current sensor output, throttle 100%, no capacitor

![50% (cap)](https://user-images.githubusercontent.com/2843378/54898544-cc124880-4edd-11e9-85ee-dca5299b10a5.png)
Current sensor output, throttle 50%, 470uF 35V capacitor

![75% (cap)](https://user-images.githubusercontent.com/2843378/54898547-ce74a280-4edd-11e9-8889-d0f2373fcf71.png)
Current sensor output, throttle 75%, 470uF 35V capacitor

![100% (cap)](https://user-images.githubusercontent.com/2843378/54898549-d03e6600-4edd-11e9-92f2-717a917288d5.png)
Current sensor output, throttle 100%, 470uF 35V capacitor

**Comment by wx4cb** [comment]
high side current sensor???? there's only 1 current sensor on the board afaik... but that aside, yes it does seem like you have a VERY noisy esc. that's not the fault of the matek board though that's potentially a bad ESC. in that case, yes, adding a cap would help, but it doesn't fix the underlying problem

**Comment by Avegawanderer** [comment]
High side current sensor is a kind of current sensor where shunt is injected in supply rail. Low side, as opposite, means that current sensor is injected into GND rail. High side sensors use differential amplifier or current mirror adding some gain to voltage drop on the shunt itself, see for example [https://www.analog.com/en/analog-dialogue/articles/high-side-current-sensing.html](url) 
or 
[https://www.st.com/resource/en/datasheet/tsc101.pdf](url)
I don't know the reason why Matek put high side sensor for this FC, possibly to keep common ground with other power contributors (maybe it's usefull for airplanes).
And yes, I tried other ESC (Turnigy plush 30A), but the noise was about the same (similar to last three pics).
It would be nice to see one's pics from the same point with different ESC and compare them to what I've got.

**Comment by shellixyz** [comment]
AFAIK All the FCs are using high side sensing

**Comment by lun606** [comment]
I fine the problem...
I change back the stock esc(use one shot) everything will be good.
But why i use Hobbywing X-Rotor 40a dshot esc (even i setup esc to one shot or dshot) the current sensor was not work.

**Comment by madl3x** [comment]
Thank you @Avegawanderer! 👍  Based on your findings I was able to fix the current sensor on Matek F722 Wing. I placed a 1000uF 35V capacitor in parallel with the ESC.

My problem was happening on a ZoHD Nano Talon, only when using LiIon (4S @ 3000 mAh Sony VTC6) batteries. The current sensor was all over the place (showing either 0.5A or 50A mid-flight, instead of 3-5A as usual), but below 1A (motor idle) everything looked ok.

What is interesting is that I didn't have the same issue with the LiPo batteries that I usually use for my racing drones (4S @ 1500 mAh Tattu R Line 120C). Probably because these batteries are high-discharge, the spikes aren't happening.
