### ISSUE TITLE
Unable to assign "gimbal pitch" to an output correctly

### ISSUE THREAD

**Issue by shabbirun** [iNavFlight/inav#4396]
I am trying to assign a servo for Gimbal Pitch in the mixer to my existing Quad X setup in 2.1 RC3(also tried 2.01). When I load the Quad X mixer, the four motors show mapped correctly to S1-S4.

When I add a servo, the servo replaces Motor 1 on S1 - I am unable to get it to map to S5.

What could be the issue? I am using a Matek F405 (MATEKF405) target.

Thank you!

**Comment by shellixyz** [comment]
You can't map it to S5 because of the timers linked to the MCU pins the outputs of this board are connected to. It can only be mapped to S1 (MATEKF405 target) or to S6 (MATEKF405_SERVOS6 target). See the [Matek F405 board documentation](https://github.com/iNavFlight/inav/blob/master/docs/Board%20-%20MatekF405.md#pwm-and-servos)
