### ISSUE TITLE
OLED display broken in Inav2.1 for SpracingF3 Board

### ISSUE THREAD

**Issue by leocopter** [iNavFlight/inav#4432]
## Steps to Reproduce

1. flash SPRACINGF3 (2.1) target
2. Enable Oled display in configuration
3. Watch the blank display ...
4.

## Expected behavior
Oled display was working in previous INAV releases. Same set up with multiple boards.

## Additional context

---

- FC Board name and vendor: SPRACINGF3
- INAV version string:  INAV/SPRACINGF3 2.1.0 Feb 25 2019 / 16:48:44 (65b0ec142)
# GCC-7.3.1 20180622 (release) [ARM/embedded-7-branch revision 261907]

**Comment by leocopter** [comment]
Hi. The OLED display is blank in INAV2.1 on the SpracingF3 board. It worked perfectly till INAV2.0.
I tested it on several boards and displays.

**Comment by wx4cb** [comment]
as per the release notes:

INAV 2.1 is the last release of INAV that fully supports F3 and especially Omnibus F3 boards. Due to the lack of flash and RAM, future versions of INAV will either remove functions on F3 or not support those boards at all. STM32F3 are strongly discouraged for new builds and existing builds should be upgraded to F7 boards

as far as I know, oled support was removed from some of the F3 boards. I would suggest either compiling your own version or upgrading to at least an F4 board

**Comment by leocopter** [comment]
Thanks for your answer. I read correctly that 2.1 was the last version to
fully support F3 boards.
I can compile my own but I can't find what to add to target.h to enable the
Oled display.
Any suggestions ?
Thanks.
Chris

**Comment by wx4cb** [comment]
it was removed to make RAM/Flash space for other things. as for what to add i'm not certain. I would have to defer to @teckel12 or @digitalentity for that one

**Comment by shellixyz** [comment]
@leocopter Add this to `target.h` to enable it again:

```
#define USE_DASHBOARD
#define USE_OLED_UG2864
#define DASHBOARD_ARMED_BITMAP // skip this to save space
```

You might need to disable other stuff like the GPS/RX/telemetry protocols you're not using in `target/common.h` for the firmware to fit in flash.

**Comment by leocopter** [comment]
Eureka ! shellixyz. you're the man ! 
I added : 
#define USE_DASHBOARD
#define USE_OLED_UG2864
#define DASHBOARD_ARMED_BITMAP
and I removed the Rangefinder stuff to save some space : the Oled is back.
Thanks !

**Comment by shellixyz** [comment]
Awesome :slightly_smiling_face:
