### ISSUE TITLE
Foxeer F405 compass not recognized

### ISSUE THREAD

**Issue by rchoughton** [iNavFlight/inav#4572]
I have been going through an iNav Install for the first time. I took a betaflight copter that I had and added a GPS/compass to it. The GPS is showing up fine in both betaflight and iNav. I cannot seem to get the magnetometer to show up.
I have a Foxeer F405 flight controller, a RDQ 880 GPS/Compass wired to it. I also have a Ublox NEO-M8N that I wired up as well and have the same problem
The Mag icon in iNav just stays grayed out.
Any suggestions on where to start or what might be wrong?

**Comment by shellixyz** [comment]
You just have to connect the SCL/SDA lines to the FC. If the compass is not recognized it is either because it is not supported or because it is an IST8310 which is supported but in 2.1.0 it looks for it at the wrong address. Once you connected the compass don't forget to set the compass type to AUTO in the configuration tab
