### ISSUE TITLE
No connection diagram is shown on this wiki page

### ISSUE THREAD

**Issue by expipiplus1** [iNavFlight/inav#4591]
https://github.com/iNavFlight/inav/wiki/iNav-with-the-FuriousFPV-F35-Lightning-FC

**Comment by parchedpacha** [comment]
I looked up the dude who made the first commit to that page, nitr0123, aka Nitro_123 on some other sites, and the person has a real name too, unfortunately this person hasn't made any more commits and has a VERY common name so Idk if you'll be able to find this person to ask for that image.

If you manage to figure it out, this would be an excellent way to make your mark on this project.

**Comment by giacomo892** [comment]
Page has been removed since it was incomplete and provided no info.
You can link your crossfire receiver to an additional serial port and enable MSP there. Then with bluetooth on the TX you can connect to the PC and configure the FC remotely.
You can also configure your FC using MSP over CRSF for instance and it should work.

**Comment by expipiplus1** [comment]
Thanks for the info!
