### ISSUE TITLE
G-force limiter

### ISSUE THREAD

**Issue by Fluburtur** [iNavFlight/inav#4745]
G-force display and alarms were added to 2.2 RC1 (thanks shellixyz)

A G-force limiter would be useful as well, its behavior would be fairly simple:
If maximum G-force is exceeded, reduce elevator until it reaches the limit (if G-force is at 5G and programmed for a max of 3, elevator will be reduced until it maintains 3Gs)

Disabling it below a certain alt would be needed in case an emergency pull-out is needed to avoid crashing into the ground (I had my glider flip out several times while in loiter and the pull-out was probably well in excess of 3Gs)

**Comment by MrLAtt** [comment]
I would also like this feature very much, but think a slightly different operation would be much better. 

I would propose that it would ramp up the input up (hopefully this could happen within 1-2 seconds) until the point where it meets the set g-force limit. Currently whenever I'm in nav modes with my more delicate planes I’m worried that it'll put itself into a situation where it will rip the wings/tail off (which is a pretty serious concern for larger/weaker models (such as motor gliders)).

Obviously, this would have to be selectable in the configurator since some people would not want this delay in control, and preferably you could select to have it disabled in passthrough mode or acro mode, or both.

I would also want it to stay under the g-force limit under any circumstance since I would prefer the plane just crashes, rather than snapping the wings/tail and then crashing.

My solution up until this point has just been to have very small bank/climb/dive limits along with allowing only up to 40% throttle when the fc has control. But of course, this has severe limitations.
