### ISSUE TITLE
Barometer on 2.1.0

### ISSUE THREAD

**Issue by ftpn** [iNavFlight/inav#4774]
Hi, i have a SPRACINGF3EVO with a working mbp280 barometer using inav 1.7.1 , the fc is a clone that does not come with a on board barometer, i added one to UART1, to get it working i had to make the following changes to "src/main/target/SPRACINGF3EVO/target .h" (thanks to anbello from rcgroups forum)
```
#define USE_I2C
//#define I2C_DEVICE (I2CDEV_1)
#define I2C_DEVICE (I2CDEV_2)   // this line changed

#define I2C2_SCL                PA9   // this line added
#define I2C2_SDA                PA10   // this line added
```
i tried to make the same changes to inav 2.1.0 but my barometer no longer works.
I noticed a couple of changes to "src/main/target/SPRACINGF3EVO/target .h", like

```
#define BARO_I2C_BUS            BUS_I2C1 //on line 51 and
#define USE_I2C
#define USE_I2C_DEVICE_1` //on lines 96, 97.
```

The changes i copied from a guy called anbello from rcgroups and it worked so far.
I dont have the knowledge to make it work on the new version.
Any help is appreciated.

**Comment by teckel12** [comment]
@ftpn Have you tried 2.1.0 without any changes at all?  Maybe barometer support wasn't in 1.7.1 but has since been added?  I've used the SP Racing F3 EVO's barometer without any modification.

**Comment by ftpn** [comment]
> @ftpn Have you tried 2.1.0 without any changes at all? Maybe barometer support wasn't in 1.7.1 but has since been added? I've used the SP Racing F3 EVO's barometer without any modification.

teckel12 im using a clone without a on-board barometer or without a I2C port, i added a external barometer to UART1 with the modifications remapping UART1 to I2C, don`t quote me on that, it`s what i understand from the changes and it works.
If you are also using a external barometer to what port did you connected your barometer?

**Comment by teckel12** [comment]
I was using an on-board barometer. I also no longer fly with that FC so I can't really help.

**Comment by TimelessNL** [comment]
I'm working on a F3 board (Micro 32bits F3 EVO V2.0)
![Micro F3_evo_v2 0_brush](https://user-images.githubusercontent.com/10838968/60402682-208b2b00-9b93-11e9-9e8b-61dd984f8fc7.jpg)
And also trying to get I2C working. I took a brief look at the code and it seems that all sensors use BUS_I2C1 while you're changing the pins for BUS_I2C2.

Could you give this a try?
```
#define USE_I2C
#define USE_I2C_DEVICE_1
#define I2C1_SCL                    PB9       
#define I2C1_SDA                    PB10 
```

**Comment by TimelessNL** [comment]
**Solution:**
Ok, the following **WORKS**.
(_kinda, if you don't use PPM or remap PPM to another pin_):
```
#define USE_I2C
#define USE_I2C_DEVICE_1
#define I2C1_SCL                    PA14 //TX UART2    
#define I2C1_SDA                    PA15 //RX UART2
```
**Extra info:**
UART2 is chosen since had I already soldered the SDA/SCL sensor wires to these pins.
I did test UART1 as well but was unable to get i2c to work in this port.
~~There is however something strange, at first I though there was something with my sensors and/or pull_up resistors, since I got massive (+10k) i2c errors and only my _BMP180_ was detected while my _QCM5883L_ did not. Also the CPU load is over 600%.~~

~~**Problem:**
After some _try & error_ I discovered that this had something to do with the RX setting :/.
The SPRACINGF3EVO's default RX mode is set to PPM:
`#define DEFAULT_RX_TYPE RX_TYPE_PPM`
When I set it to anything else (in my case iBUS) i2c works perfectly _(zero i2c errors)_ and all attached sensors are detected~~

~~**Question:**
Does anyone else experience "_RX PPM mode_" issue with i2c?
I do not have any PPM receiver connected though,
to be more precise there isn't any receiver attached at all (yet).
But find it strange that if there is no receiver present that iNav is on the verge of crashing.~~

**Update:**
Ah... I think I understand why I got massive i2c errors, PA15 is used for PPM:
_inav/src/main/target/SPRACINGF3EVO/target.c_ 
```
const timerHardware_t timerHardware[] = {
    // PPM / UART2 RX
DEF_TIM(TIM8, CH1, PA15, TIM_USE_PPM, 0), // PPM
```
And since I'm using PA15 for SDA there is a resource conflict. My board uses UART3_RX as receiver input, so I guess I have to remap that port as well and all will be fine :).
