### ISSUE TITLE
dynamic compass compensation

### ISSUE THREAD

**Issue by elepete** [iNavFlight/inav#4820]
## Current Behavior
Magnetometer must be placed distant to power cables / battery to avoid magnetic interference. But typically not all current interference can be eliminated.

## Desired Behavior
Current flow magnetometer offset could be compensated if calibrated vs. current.

## Suggested Solution
Needs in any case a board with current measurement.
A calibration could be done in a leveled ascent / descent without any yaw turn. In that condition magnetometer does (should) not change. A value table with mag x, y, z values vs. current could be stored to find the offset per ampere.
As the build geometry is fixed, the interference will be repeatable and the magnetometer read should be more stable.

## Who does this impact? Who is this for?
All users, that want to reduce current interference to magnetometer.
Could help with builds that have proximity between magnetometer and power cables / battery.

**Comment by elepete** [comment]
I have looked to two flight logs that I have produced to see the blackbox data:
1. Compass mounted distant on mast:
Low interference even with 30 A delta to mag x, y, z data (kept the quad within 0.05g on x- and y-axis max. of 3° tilt)
2. Compass mounted close to battery (short mast):
Interference is visible in mag x, y, z data (again quad within 0.05g max on x- and y-axis)
From the log data I find it hard to make out an automatic calibration, there is too much sources of errors possible. Any idea is welcome.

An alternative idea: Strap the quad. stationary (as Joshua Bardwell does to calibrate the current sensor) and take the data from the blackbox. I will try that at a later point. That could than be manually calculated and entered as compensation.

**Comment by hali9** [comment]
I've seen it already somewhere https://github.com/iNavFlight/inav/issues/93 https://github.com/iNavFlight/inav/pull/214

I do some check and what I have:
![interferencje](https://user-images.githubusercontent.com/23119651/62358966-253a5a80-b516-11e9-83b3-211130411099.png)
In my quad, the compass is glued to the body on top and the compass reacts to the current flowing.
It's very easy to read from here what compass compensation should be depending on the current.
I note that in this quad does not work poshold nor rth, I have to use a 7cm mast for the compass to have rth and a minimum of 3cm mast for efficient poshold otherwise the quad flies away.

I also find article about compass interferencing:
https://www.wired.com/story/can-your-electronic-gadgets-interfere-with-your-compass/

It may be very helpful to rout the power cable and ground together.
