### ISSUE TITLE
VTX Power switching in flight

### ISSUE THREAD

**Issue by craigywsm** [iNavFlight/inav#4864]
Hi All,
Please could someone tell me how to change VTX power in flight assigned to a switch?
I have tried using the adjustments page with no luck
Currently using INAV 2.1 with the Matek F722 wing board with the Matek VTX-HV with IRC TRAMP

**Comment by teckel12** [comment]
@craigywsm I don't think you can from a switch. But you can from the OSD menu via stick commands. See here:

https://github.com/iNavFlight/inav/blob/development/docs/Controls.md 

Of course, that's not in-flight. For in-flight, I believe your only option is to set the pre-arm and arm transmitter level, which in my opinion works great. I have mine set to be 25 mW before launch, goes to 600 mW at launch, and says at 600 mW when disarmed (in case of a crash where getting a view from the camera could help locate the model). There's a setting also that would take the power back down to the lowest power on disarm, if that's what you want. 

See the `vtx_low_power_disarm` option for details.

**Comment by craigywsm** [comment]
Thanks for your info teckel. 
Just done some research and found it on the latest 2.2.0 release so i will need to upgrade and re test with the adjustments the setting must have been there for future implementation 
https://github.com/iNavFlight/inav/releases
![Capture](https://user-images.githubusercontent.com/40343747/59968707-ffdd2880-9535-11e9-9734-ad0493c78c45.PNG)
Could really do with some documentation on how this works if at all possible.
Happy to lend a hand writing it if someone can point me in the right direction.
This might need further development as may need to store the power levels as each vtx has different power levels.

**Comment by teckel12** [comment]
@craigywsm That's a new feature I wasn't aware was added! =)  I assume it would be done via the Modes tab like all other switch-based controls are configured.

The state of power levels is a mess, There will be no way that INAV can keep up with the different models that are released every week with totally different power levels.  Best to just set it to 1-5 or whatever and call it a day.

**Comment by L4ky** [comment]
> @craigywsm That's a new feature I wasn't aware was added! =) I assume it would be done via the Modes tab like all other switch-based controls are configured.
> 
> The state of power levels is a mess, There will be no way that INAV can keep up with the different models that are released every week with totally different power levels. Best to just set it to 1-5 or whatever and call it a day.

No, this function is handled by Adjustments tab.
Just choose your activation switch ( it could be the arm switch ), VTX power level in the dropdown menu, and the command switch which will be the one that will increase/decrease the value.
My advice is to use a 3-pos switch or a stepped-potentiometer ( i don't know the exact name ).

Remember: you don't have to keep your switch up or down too much or you will make more than one step.

Try that on the ground to learn its effectiveness.

P.S. Add VTX power on OSD to see current power level

**Comment by CapnBry** [comment]
There's a great video on setting it up and using it on youtube [iNav 2.2.0 VTX power change in flight](https://www.youtube.com/watch?v=Vd6EBr4QYa8) from NoAgenda FPV. I also wasn't aware of this feature until he posted the video. Skip to about 1:30 in the video to get to setting it up.

**Comment by P-I-Engineer** [comment]
i'd prefer this was in modes as well, or is there a way to do position based values instead of incrementing?

if it was modes, i would use a 3 pos switch and set my max values in opentx to set the power level to the switch position.

**Comment by L4ky** [comment]
Actually you can not assign values based on position.

You can only increase or decrease current value.

**Comment by craigywsm** [comment]
CapnBry many thanks great video will test this on my setup.
P-I-Engineer and L4ky. Yes it will be like the PID adjustment theory.
I see there could be an issue here as all vtx's have different power levels might be worth adding settings for the ones the VTX can support. Not sure on how the Tramp / Smartaudio with handle the changes
e.g 25mW , 100mw, 500mw
or 25mw, 200mw, 800mw???
With a county override

**Comment by P-I-Engineer** [comment]
my workaround for time based incrementing is going to be a "duration" logical switch. So that moving switch up will increase by one, then back to middle, then back to up to increase again. Same for decrease. That way you don't have to time it with your fingers.

using telemetry you could have it auto increase also with logical switches, but that's not the smartest way to do it, since it's a blind effort.

**Comment by L4ky** [comment]
> CapnBry many thanks great video will test this on my setup.
> P-I-Engineer and L4ky. Yes it will be like the PID adjustment theory.
> I see there could be an issue here as all vtx's have different power levels might be worth adding settings for the ones the VTX can support. Not sure on how the Tramp / Smartaudio with handle the changes
> e.g 25mW , 100mw, 500mw
> or 25mw, 200mw, 800mw???
> With a county override

The logic behind all this is "power levels" which are (usually) number from 1 to 5. 25/100/200/500/800 are just labels but they don't exists in the protocols..

At the moment most vtx have 4 or 5 different power levels so not a big issue there.
The problem will be in the future if power level count will increase.

Another user is working on this.. i think you'll see something soon

**Comment by P-I-Engineer** [comment]
here's my opentx work around for 1 position increment.
the duration will need to be tweaked. I haven't tried this on my plane yet, just in companion.

![image](https://user-images.githubusercontent.com/11393479/60031449-a241fc80-9659-11e9-83cf-f464d8baac44.png)

![image](https://user-images.githubusercontent.com/11393479/60031317-5a22da00-9659-11e9-9d7f-ceb726253131.png)

**Comment by noagendafpv** [comment]
> There's a great video on setting it up and using it on youtube [iNav 2.2.0 VTX power change in flight](https://www.youtube.com/watch?v=Vd6EBr4QYa8) from NoAgenda FPV. I also wasn't aware of this feature until he posted the video. Skip to about 1:30 in the video to get to setting it up.

Thanks for sharing, I just stumbled on this and was going to post the link, but you beat me to it.

Now I have to try what PI Engineer did for Auto switching.

**Comment by teckel12** [comment]
Now we just need VTx power levels to be set automatically based on distance from home =)

**Comment by P-I-Engineer** [comment]
here's simpler mix. I set it to the throttle trim as well. I added an additional channel so it doesn't flash the whole time.
![image](https://user-images.githubusercontent.com/11393479/60069731-e3bdc080-96c8-11e9-8291-f9bbcbd11e03.png)

![image](https://user-images.githubusercontent.com/11393479/60104137-af242600-9715-11e9-9366-98ab9bf07a7e.png)

![image](https://user-images.githubusercontent.com/11393479/60105999-3e7f0880-9719-11e9-8789-80f43b1d6e05.png)

![image](https://user-images.githubusercontent.com/11393479/60069754-f637fa00-96c8-11e9-8e92-7def4cf8c288.png)

**Comment by Jetrell** [comment]
Hi guys. 
To all you that have tried this VTX power level change.
I played around a bit with Companion, while i'm away. But have no way to test it for some weeks.

This OpenTX combo of Logic switches and Special functions. Seems to work in the simulator. 
I was wondering if one of you guys with an OpenTX radio could try it out and report back on how it works. 
It should perform more like a mode function. It has 4 positions (disarmed 25mw, Pos1, Pos2 and Pos3) I based it on a Unify 25, 200, 500 and 800.

It uses the arming switch to return to VTX to 25mW, when disarmed, and holds it at the lowest position.  

Then when the armed, it looks at the location of the 3 Position power selector switch. And from that it selects the appropriate timer required to place the VTX power level at the selected switch position. 
It will also speak the power levels when the power level switch or disarming is toggled.

The timers will need to be altered to get it to work correctly. I just based the timers on 0.6seconds, to administer a single change in level.  1.2seconds for two changes. 1.8seconds for three changes.

The zip also contains power level audio files.

![VTX power change - OpenTX Logical switches(basic)](https://user-images.githubusercontent.com/47995726/61184518-06247780-a692-11e9-973f-6765bbb70990.PNG)

![VTX power change - OpenTX Special Functions(basic)](https://user-images.githubusercontent.com/47995726/61184519-0886d180-a692-11e9-9faa-6805c494abf5.PNG)

[VTX power change - OpenTX.zip](https://github.com/iNavFlight/inav/files/3389935/VTX.power.change.-.OpenTX.zip)

**Comment by teckel12** [comment]
@Jetrell I've been playing with something similar to automatically set the power level based on distance from home.  It's a little messy because you can't directly select a power level.

The plan is to eventually do this automatically right from within Lua Telemetry without any logical switches or special functions.  Also, this will allow selecting an exact power level instead of holding a logical switch for a certain amount of time (which is prone to not always working).  The thought is something like power level 2 at 100 feet, power level 3 at 1000 feet, etc.  Maybe even raise the power level when facing towards the pilot instead of away from the pilot (where the antenna is sometimes blocked by the model).

This could also be done in INAV, which is probably a better option.

**Comment by Jetrell** [comment]
Hi Guys. I finally got around to testing this OpenTX logic switch and Special functions mix for the VTX power control.
It uses a 3Pos switch to set 200mW, 500mW and 1000mW, plus the ARM switch to drop back to 25mW when DisARMED. 
When ARMED, it will go to what ever power level you leave the power switch in. 
I have given it a good workout, and it doesn't get muddled up. The only thing that needs to be avoided, is flicking through the 3Pos power switch too quickly. i.e. don't flick from Pos1 to Pos3 in a rush. Make sure Pos2 gets at least 0.3 of a second to register its position.

This timing was set using a Unify Pro. I haven't tested it with Tramp. 
Make sure that - `set vtx_low_power_disarm = OFF` in iNav. This is because the timing in iNav, for re-arming isn't as precise as the mixer requires.

![Logic switches VTX](https://user-images.githubusercontent.com/47995726/62982579-ea1e1c80-be6f-11e9-9a03-37fdd070e10d.PNG)

![Specail Functions VTX](https://user-images.githubusercontent.com/47995726/62982583-ec807680-be6f-11e9-8b37-3a44c59497ad.PNG)

![iNav adjustment setup](https://user-images.githubusercontent.com/47995726/62982587-eee2d080-be6f-11e9-8254-0883fffd9445.PNG)


[mW audio.zip](https://github.com/iNavFlight/inav/files/3499176/mW.audio.zip)

**Comment by DzikuVx** [comment]
Power switching in flight is possible now with 2.2 with adjustments, and in 2.3 will be a part of Global Functions. Closing. Thanks

**Comment by RomanLut** [comment]
There is a video describing how to do it in 2.6.0:
https://www.youtube.com/watch?v=g3N7e_SHSwM
