### ISSUE TITLE
Autotune might be storing Dgain instead of FFgains

### ISSUE THREAD

**Issue by DzikuVx** [iNavFlight/inav#4869]
## Current Behavior
INAV 2.2 Autotune might be storing Dgain instead of FFgains. Not 100% confirmed since it happened only on one of the axises

## Steps to Reproduce
1. Run Autotune
2. Check gains

## Expected behavior
Store FFgains as FFgains and Dgains should be 0 on fixed wings

**Comment by digitalentity** [comment]
Confirmed via reading the code. Fix pending

**Comment by CapnBry** [comment]
The D/FF values are also not being logged to Blackbox (#4839), and their setting isn't included in the blackbox info header, nor are they showing in the OSD since the extra field was added to the PID struct. There were a bunch of small things broken by adding this late change that need to be found and cleaned up now.
