### ISSUE TITLE
Gyro Fusion for Inav

### ISSUE THREAD

**Issue by jukkaaakko** [iNavFlight/inav#5614]
## Current Behavior
Dual gyro FC's especially using ICM20689 gyros are bit twitchy. The boards are dessigned to use both gyros simultaneously  by averaging data from both gyros. Inav has dual gyro support, but it is using only one gyro at the time, so using  ICM20689 is bit itcchy...

## Desired Behavior
Read both gyros and make data smooth.

## Suggested Solution
Implement "gyro fusion".

## Who does this impact? Who is this for?
Dual gyro users and this would make dual gyro boards more usable with inav

## Additional context
I attached patch from my prototype/proof concept implementation. It's not yet fligth tested but on desk it gives pretty  smooth data on my iFligth F7 twing FC. Work is done on top of 2.4.0 release. 
[gyro_fusion.patch.zip](https://github.com/iNavFlight/inav/files/4529886/gyro_fusion.patch.zip)
[gyro_fusion_tasks.txt](https://github.com/iNavFlight/inav/files/4529909/gyro_fusion_tasks.txt)

**Comment by jukkaaakko** [comment]
After first hovers with my modifications I noticed that there is a slight math problem with gyro scaling in my patch. I got that sorted, version 2 will be here soon.

**Comment by jukkaaakko** [comment]
This v2 flies really nicely. Code is still ugly, so we should take some betafligth influences in.
[gyro_fusion_v2.patch.zip](https://github.com/iNavFlight/inav/files/4531617/gyro_fusion_v2.patch.zip)

**Comment by romko1** [comment]
Hi,
in the next few days I will receive a board that has two gyroscopes ICM20689. I want to ask you, have you progressed further? Because I don't want to switch to betaflight. Thank you.

**Comment by maganaluis** [comment]
i was looking to use the dual gyro h7 board from tbs, i have it working with a 10 inch build and just upgraded to inav 9, i see this was closed but not sure if it was implemented

really the main reason of the dual gyros is redundancy, so is gyro fusion best? or does inav 9 just switches between them if one of them becomes noisy? I can't find much information about it

**Comment by sensei-hacker** [comment]
The important differences between these three classes sometimes isn't immediately obvious, but they are important:

1. Two independent sensors (baro and GPS)
2. Three sensors
3. Two of the same sensor

Two independent sensors can be fused effectively (cross-validation). While the baro is affected by turbulence, the GPS isn't. So the two independent sensors can be effectively mixed.

If you have THREE sensors, you can have a vote. If two sensors agree and one disagrees, you can throw out the oddball.

If you have two of the same sensor, you can't vote. And they will both be picking up the same vibration, giving the same wrong reading. So they don't compensate for each other's weaknesses like a baro and GPS do.  So you don't gain much of anything trying to use both at the same time. But you DO double your chance of many problems!

If you average a correct reading with a wrong reading, you end up with a wrong result. Making sure your result is wrong if EITHER of two gyros is wrong doubles the opportunity for wrong results, except those caused by correlated causes that cause both of them to be wrong.

So trying to use both at the same time mostly makes things worse.

INAV allows you to choose between the two gyros depending on what type of flying you are doing. Typically there is a faster one and a more precise one or whatever. Choose which one fits you best.
