### ISSUE TITLE
Autotrim only applying midpoint offset to one aileron

### ISSUE THREAD

**Issue by mattcave** [iNavFlight/inav#5753]
## Environment

FC: Matek F722 Wing
Firmware: iNav 2.4 (believed to still be present in 2.5 RC1)
Airframe: Finwing AlbaBird. ie conventional tail aircraft.

## Current Behaviour

I have two aileron servos on outputs S1 and S2. When I auto trim, iNav applies the midpoint offset to ONE aileron but not the other. e.g. servo midpoint for one will still be 1500us, the other will be, say, 1460us. 

## Steps to Reproduce

1. Configure mixer with two ailerons on S1 and S2
2. Arm. Enter auto trim mode and apply left stick during auto trim. 
3. Disarm.
4. Examine outputs tab. One servo, in my case S2, is set to 1460us, other servo (S1) is still 1500.
5. Observe control surfaces on plane. One servo is offset as expected, the other is still at neutral position.

## Expected behavior
After auto trim, both servos should be deflected by an equal amount in opposite directions. e.g servo 1 should be at 1460us, servo 2 should be at 1540us.

## Suggested solution(s)

Looks like a bug with new midpoint only being applied to one output. 

## Additional context

CLI dump:
https://pastebin.com/RrwALRzx

Configurator Screenshots
![Screen Shot 2020-05-18 at 9 11 33 AM](https://user-images.githubusercontent.com/5394668/82217763-e6c92d00-98e8-11ea-8aab-8c02cbfc6aee.png)
![Screen Shot 2020-05-18 at 9 12 14 AM](https://user-images.githubusercontent.com/5394668/82217765-e761c380-98e8-11ea-8496-49e9702d07f7.png)
![Screen Shot 2020-05-18 at 9 12 29 AM](https://user-images.githubusercontent.com/5394668/82217767-e7fa5a00-98e8-11ea-9ca9-847fd01b85be.png)

**Comment by nikram77** [comment]
I can confirm. Same behavior on my F722 Wing (also conventional tail airplane), Autotrim only applies to S2, S1 stays at 1500us.

edit.
I tested on F405STD+FCHUB-W with version 2.2.1 - everything worked correctly. After flashing 2.4 S1 aileron gets new midpoint, S2 stays at 1500us. No matter what mixer is configured (classic airplane, vtail) autotrim ignores second aileron servo.

**Comment by leeph** [comment]
I can confirm same behaviour on Matek F722-Wing using V-tail preset.

**Comment by Arvycka** [comment]
Restore default servo mapping from the template. aileron servos must have numbers 3 and 4. rudder - 5, pitch - 2. Inav mixer is weird, autotrim might not work correctly if you change servo numbers from the default ones.

**Comment by leeph** [comment]
'the template' - what template?

If you are talking about mixer presets, then I am using the mixer preset in iNav for Mini Talon V-Tail. Stabilised roll is assigned on outputs S1 and S2 by default on F722-Wing, which is where I have them plugged in, as does Matt. Even if I were to follow that advice, it would not help much on a V-tail since pitch and yaw are mixed, so there is no one pitch servo, and no one yaw servo.

You are right, the iNav mixer *is* weird, it's like the left hand doesn't know what the right hand is doing, half the time. It's not very well implemented and needs rewriting to be more logical, IMO.

**Comment by Arvycka** [comment]
I mean servo numbers on the left, not the FC pads. Load mixer and apply,
then keep those numbers as they are.

2020 m. geg. 20 d., tr 17:31, James Mills <notifications@github.com> rašė:

**Comment by leeph** [comment]
![image](https://user-images.githubusercontent.com/9444485/82459678-21c98d00-9ab0-11ea-9927-8b950efda7a6.png)

I have not changed them. The servo numbers are exactly as per the mixer preset for Mini Talon V-Tail.

Stabilised roll (ailerons) are on 'Servo 2' and 'Servo 3' which correspond to FC outputs S1 and S2.

In my case, since it's a V-tail, I can't use the standard Airplane preset because the pitch and yaw functions are mixed to two servos at the tail. I suppose I could try fudging the Airplane mixer with extra mixer lines to make this work, but it seems to me the mixer preset needs fixing for this F722-Wing target such that Autotrim correctly applies to servos with the stabilised roll input.

This seems to be the crux of the problem.

It seems wrong that iNav expects to see servos on particular outputs since this defeats the object of a customisable mixer. If it was re-coded such that Autotrim first looks at what inputs are assigned and applies the trim to servos associated with those inputs, we would not be having this problem.

**Comment by nikram77** [comment]
If specific outputs need to be on specific pad/number - what`s the point of customizable mixer??
And I wan`t to remind that it isn`t happening only on F722 Wing. I reproduced this on F405 Std and Omnibus F4 Pro since my last comment. And on all this boards with 2.2.1 issue doesn`t exist (all this boards had 2.2.1 allready and worked fine), so it`s definitely 2.4 bug.

**Comment by Arvycka** [comment]
If spare channels are available, I find it much better to trim via aux
channels. Autotrim as it is is difficult to use and hardly ever works
anyway because of issues like above.

2020 m. geg. 23 d., št 17:33, nikram77 <notifications@github.com> rašė:

**Comment by leeph** [comment]
> 
> If spare channels are available, I find it much better to trim via aux channels. Autotrim as it is is difficult to use and hardly ever works anyway because of issues like above. 

This could certainly be a workaround but this issue is for rectifying the bug in the code, which still exists as of iNav 2.5 RC2.

**Comment by digitalentity** [comment]
@leeph can you please share your full configuration diff?

**Comment by leeph** [comment]
Of course: https://pastebin.com/c5BVUeHx

Note that although I have a slightly non-standard config for the tail servo mixer, the aileron servos are plugged into S1 and S2 which is exactly as the Airplane V-Tail preset calls for, and this is where the issue manifests. Autotrim is applied only to the left wing aileron on S2, and not the right wing aileron on S1.

**Comment by leeph** [comment]
Can we revisit this please? There needs to be a way to define which servos get autotrimmed if one configured the mixer servo outputs differently than the platform default.
