### ISSUE TITLE
Abnormal throttle behavior in Angle/Horizon mode 

### ISSUE THREAD

**Issue by sammichael25** [iNavFlight/inav#5957]
****

## Current Behavior

When I arm the quad for flight (with propellers on), when I apply throttle the motors start increasing exponentially. eg. I can arm and apply 30% throttle and not move the throttle stick and the motors will speed up well past 30% and keep increasing. When i drop the throttle back to zero to avoid the quad taking to the skies it drops temporarily and with the stick still at 0% it spools up again. I can only regain control by either switching to acro or disarming to prevent fly away.

Possible duplicates
-#5790
-#5772
-#5009
-#4925

## Steps to Reproduce

1.Arm quad
2.Switch to Horizon or Angle mode
3.Apply throttle to attempt to hover quad

## Expected behavior

Proper throttle control

## Additional context

CLI Dump
[https://pastebin.com/FEpxJafb](url)
Blackbox Log attached
[blackbox_log_2020-07-18_175142.TXT](https://github.com/iNavFlight/inav/files/4942825/blackbox_log_2020-07-18_175142.TXT)

- FC Board name and vendor: KakuteF4V2
- INAV version string: 2.5.0

**Comment by DzikuVx** [comment]
![image](https://user-images.githubusercontent.com/966811/87972409-24079200-cac7-11ea-86c9-100cbade4d63.png)

Well, the blackbox log shows slightly different story and shows that everything is like it should be

1 - when you throttle up slightly, motors 1, 2 and 4 accelertate to match throttle input. Motor 3 is not accelerating and that suggests that quad is not level, but tilted
2 - when you thorttle up stronger, all motors accelerate and Quad gets airborne. Bear in mind that motors are at around 30% of power only
3 - when you cut thorttle quad lands but since both Angle and Airmode are enabled, it tries to keep level. Since your quad is tilted or there is a measurement error that makes INAV think that it's tilted, it spins out motors 1, 2 and 4 to keep level. 

What to do:
- verify FC leveling and calibration
- disarm after landing
- limit Angle mode usage to "only in the air"
- change Airmoide type to "STICK_CENTER"
