### ISSUE TITLE
Failsafe detect issue (MatekF722-Wing, R9MM-ACCST FPORT)

### ISSUE THREAD

**Issue by Avegawanderer** [iNavFlight/inav#5982]
When powering on flight controller and receiver and leaving transmmitter powered off, failsafe is not detected by flight controller. Failsafe flag in configurator is not active, OSD shows "Unable to arm: roll/pitch not centered" instead of Failsafe indication. After powering ON and OFF thransmitter, failsafe is, however, detected correctly.
List of hardware:
Matek F722-Wing,
FrSky R9MM-ACCST (2018), connected through FPORT
Broken in 2.5.0 and 2.5.1, works as expected in 2.4.0.
I have two similar setups with F722-Wing and R9MM, they both behave this way.
Tried: re-binding receiver, re-flashing FC with full erase with no success.

**Comment by b14ckyy** [comment]
can confirm that. Just found that recently out when I have set up a plane from scratch. 
Usually I copy a lot of settings from a personal template. I usually use CH16 RSSI value to trigger failsafe mode when channel hits 1000 instead of relying on the FS detection only. RSSI channel trigger just acts faster. 

Boards discovered: F411WSE with R9mm F.Port and F405Wing with R9 Slim+ F.Port. servos go to full deflection when powered on without radio turned in first.
