### ISSUE TITLE
New Target Request; MAMBAF405US_I2C

### ISSUE THREAD

**Issue by Animetronics** [iNavFlight/inav#6535]
## Current Behavior
Unknown; 
Possible I2C pin and timer assignment conflict with the new line if Mamba MK3 boards with barometers.:
[https://www.diatone.us/collections/new/products/mamba-stack-basic-f405-mk3-40a-6s-8bit](https://www.diatone.us/collections/new/products/mamba-stack-basic-f405-mk3-40a-6s-8bit)

## Desired Behavior
A new target , MAMBAF405US_I2C with the new resource assignments.

## Suggested Solution
Porting over these new assignments from 
[https://raw.githubusercontent.com/betaflight/unified-targets/master/configs/default/DIAT-MAMBAF405US_I2C.config](https://raw.githubusercontent.com/betaflight/unified-targets/master/configs/default/DIAT-MAMBAF405US_I2C.config)

It appears that the pins for I2C are different from the existing MAMBAF405US target:
[https://github.com/iNavFlight/inav/tree/master/src/main/target/MAMBAF405US](https://github.com/iNavFlight/inav/tree/master/src/main/target/MAMBAF405US)

The following would be replaced in the MAMBAF405US target.h :

#define I2C2_SCL                       PB8 // was PB10 SCL pad TX3
#define I2C2_SDA                      PB9 // was PB11 SDA pad RX3
#define DEFAULT_I2C_BUS         BUS_I2C1 // was I2C2

## Who does this impact? Who is this for?
New users of the upcoming MAMBAF405 MK3 stacks with integrated barometers.

## Additional context
The new board layout can be seen here:
[https://cdn.shopify.com/s/files/1/0027/2708/4144/files/6-MAMBA_Basic_F405_MK3.pdf?v=1610714257](https://cdn.shopify.com/s/files/1/0027/2708/4144/files/6-MAMBA_Basic_F405_MK3.pdf?v=1610714257)

**Comment by Animetronics** [comment]
The following modded hex file has potentially fixed the issue:
[TEST_MAMBAF405US_I2C.zip](https://github.com/iNavFlight/inav/files/5964693/TEST_MAMBAF405US_I2C.zip)

**Comment by sq-meng** [comment]
I was not able to test the attached 2.7.0 build due to the lack of a suitable configurator. But...
Compiling from 2.6.1 source making the mentioned modifications, motor 4 won't spin if DSHOT protocol was selected. ONESHOT125 worked fine. I had additionally changed the line
#define USE_I2C_DEVICE_2 to 1, but that didn't make a difference.
The BF config file used a different DMA channel allocation scheme. I tried to change the target.c file and that seemed to work - all 4 motors spin under DSHOT300 now.
The change  to target.c was:
from
DEF_TIM(TIM1,   CH2,  PA9,   TIM_USE_MC_MOTOR | TIM_USE_FW_MOTOR,  0, 1 ),     // S4_OUT – D(2, 2, 6)
to
DEF_TIM(TIM1,   CH2,  PA9,   TIM_USE_MC_MOTOR | TIM_USE_FW_MOTOR,  0, 0 ),     // S4_OUT – D(2, 2, 6)
Not sure if I traded one problem with another, but hope that helps.
