### ISSUE TITLE
Mission Planer - let user set waypoints as absolute values / above meter sea level

### ISSUE THREAD

**Issue by poi2poi** [iNavFlight/inav#6641]
## Current Behavior
Waypoints are defined as meters above ground.

## Desired Behavior
Sometimes you don't know yet where you want to launch your wing, i.e. because of wind conditions not allowing a start on a certain site

## Suggested Solution
Let user set waypoints in Mission Planer that are defined by meters above sea level

## Who does this impact? Who is this for?
People flying missions with Mission planer, as well important to respect restricted airspace, that might not allow to fly above a certain altitude

**Comment by breadoven** [comment]
As it happens I've come up with a change that allows you to set a mission to use a SL altitude datum rather than the usual takeoff altitude datum. You just need to create a mission using altitudes relative to SL then upload to the FC. In order to get it to work with the SL datum you set the flag of WP 0 to 1 in the CLI WP settings, e.g.
wp 0 1 326917905 39228274 26539 0 0 0 1
wp 1 1 326905956 39205917 24539 0 0 0 0

This sets the whole mission altitude datum to SL.

Had a couple of test flights and it works well for missions loaded via the CLI, can't vouch for anything loaded any other way. The GPS altitude log tracks the WP altitudes set in the mission file exactly. Big benefit is the flight altitude is independent of TO altitude, so makes it easier to setup missions flying close to terrain, no need to worry about where you launch from.
