### ISSUE TITLE
Altitude reading decimal places

### ISSUE THREAD

**Issue by Energeezer** [iNavFlight/inav#6815]
Using Baro on 2.6 my altitude ladder is set to feet but only reads up tp 99 feet then starts at 1 again.

**Comment by MrD-RC** [comment]
You need to move the OSD element. Some of the numbers are getting hidden by other elements.

**Comment by Energeezer** [comment]
> You need to move the OSD element. Some of the numbers are getting hidden by other elements.



> You need to move 


> You need to move the OSD element. Some of the numbers are getting hidden by other elements.

OK. Sounds good. I'll give that a try. While I'm here is there a way to show distances in metric and altitude in feet? Seems the settings are global.

**Comment by MrD-RC** [comment]
Try the UK settings. That has some things in imperial, others in metric. But I think it’s the other way around, distance in imperial and altitude in metres. I’m from the UK and prefer imperial. The only thing that would annoy me is temperature in F rather than C. I’d rather have distance and altitude in imperial though.

**Comment by avsaase** [comment]
Looks like this is resolved.
