### ISSUE TITLE
Disarm Logic Discussion

### ISSUE THREAD

**Issue by JyeSmith** [iNavFlight/inav#7017]
I was looking at the disarm logic and would like to make sure I understand it correctly :)

From the link below it looks like disarm requires a disarm command, and then a timeout of 250ms before actually disarming.

https://github.com/iNavFlight/inav/blob/7ccf7a65304423a42f567bc95ba39425885f305b/src/main/fc/rc_controls.c#L213

And the default failsafe timeout is also 500ms.

A big reason users fly INav is for the FS and RTH feature.  At the point of FS you have the highest chance of a RC packets with flipped bits due to a weak signal, and a very small chance that one of these packets may not be detected by the CRC.  So one stray packet here when you have low LQ can cause a disarm.  This can all happen before the FS timeout.

The odds of this are very very low.  But can I propose a disarm counter similar to what BF uses?  e.g. 4 disarm commands must be received before disarming.

**Comment by breadoven** [comment]
There is also rxIsReceivingSignal which will block disarm if it returns loss of signal. It gets set before the Failsafe timeout kicks in so might block disarm before the time delay expires. I think it would be better to block disarm and arming when signal problems are first detected rather than waiting for failsafe to trigger fully, see https://github.com/iNavFlight/inav/pull/6874.
