### ISSUE TITLE
[copter][failsafe] land with baro

### ISSUE THREAD

**Issue by Zataras** [iNavFlight/inav#7340]
## Current Behavior
Currently there is one automated failsafe mode - RTH which requires GPS and defining points. Many drones do not use GPS.
Second option is to set throttle to constant value. When changing drone weight, value has to be recalibrated.
Third to just stop the motors. This leads to crash.

## Desired Behavior
Why there is no option to automatically land with barometer? It seems to be quite reasonable option to me. I've tried to modify flight height with throttle stick in ALTHOLD mode and it caused smooth landing. I know baros are error prone, but software can deal with it I suppose.
Enabling alt landing mode should cause decreasing value of set altitude. At some point it will stay on the ground. Then there could be some timeout on measured altitude value not decreasing or just waiting for pilot action.

## Suggested Solution
Add "alt landing" mode which could be set as failsafe action.

## Who does this impact? Who is this for?
At least copters users. Automatic land feature would help beginners to not crash their machines in critical situations.

## Additional context
I remember using the toy drone "UGO Zephir 2.0 UDR-1358", it had automatic start and automatic land features.

**Comment by breadoven** [comment]
Emergency landing is currently triggered during RTH or WP following position sensor loss (mainly) and does allow a controlled descent rate set by `nav_emerg_landing_speed `if altitude control is working, otherwise it reverts to using a fixed throttle setting, `failsafe_throttle ,`or just Drop, depends how Failsafe has been set up. So it uses Failsafe settings to decide what happens if altitude control isn't available.

However, Failsafe appears to only allow `SET-THR` to control landing descent. The only way Failsafe could currently do a controlled descent using `nav_emerg_landing_speed  `would be if it was set to RTH and the position sensors failed causing an Emergency Landing. Not sure why it was set up this way but can't see why there would be a problem allowing a controlled descent during Failsafe if altitude control is still working rather than just `SET-THR`. Essentially it would do an Emergency Landing if Failsafe set to land.
