### ISSUE TITLE
FLYWOOF411 has incorrect pin definition.

### ISSUE THREAD

**Issue by rizacelik** [iNavFlight/inav#7466]
FLYWOOF411 has incorrect pin definition. RX should receive the receiver signal, not TX. There's been a mistake. PA2 pin is UART2_TX_PIN pin.
**DEF_TIM(TIM9, CH1, PA2,   TIM_USE_PPM,   0, 0), // PPM IN**

In fact, it should be as follows.

**DEF_TIM(TIM9, CH2, PA3,   TIM_USE_PPM,   0, 0), // PPM IN**

My English is bad, I couldn't write in detail.

**Comment by RomanLut** [comment]
I do not have FLYWOOF411 V1, it might indeed have pin marked PPM which is connected to TX2, but for Noxe V1 board it should be defined like this:

DEF_TIM(TIM9, CH9, PA1, TIM_USE_ANY, 0, 0), // PPM IN on RX2 pin (A3) 
DEF_TIM(TIM5, CH4, PA3,  TIM_USE_PPM,   0, 1), // Softserial1 TX/RX on TX2 pin (A2)

Otherwise Softserial1 will not work.
