### ISSUE TITLE
Remove TURN ASSIST when aircraft mode is multicopter as it is not supported.

### ISSUE THREAD

**Issue by Nandox7** [iNavFlight/inav#7481]
Not much to say.

Turn Assist mode shows up as one of the modes when iNav is set for a Multicopter.
Given that this only works for planes (as stated here: https://github.com/iNavFlight/inav/wiki/Modes#turn-assist) it becomes misleading and there is no point showing it up if the aircraft type is not a plane.

Not a major issue, just a small improvement.
Thanks

**Comment by digitalentity** [comment]
Turn assist works for multicopters, just differently (not as visible as on planes).

On copters turn assist makes yaw work relative to the ground rather than to aircraft.

I.e: if you are flying at 45deg pitch forward and do a 180deg yaw:

- without turn assist you will continue flying in the same direction, but will be pitching backwards 45deg (looking at the sky)
- with turn assist you will do a proper 180deg turn and fly in the opposite direction.
