### ISSUE TITLE
Review autolaunch behaviour when launch is NOT detected.

### ISSUE THREAD

**Issue by pulquero** [iNavFlight/inav#7512]
Recently, I had an incident where my wing wouldn't respond to control inputs during an autolaunch. Upon DVR review, it appears the fc did not detect the launch, and nav_fw_launch_idle_thr was sufficiently high that the wing had enough thrust to sustain a climb (and as the throw wasn't completely level, also banked to the left). I don't expect this to be 'solved' but most accidents are a result of a chain of bad outcomes, and maybe there are a few things we can do to break that chain.

## Current Behavior
In autolaunch mode, the controls are disabled until the fc detects the launch.

## Desired Behavior
Mitigate the scenario of an airborne vehicle which hasn't detected launch.

## Suggested Solution

1.  I think the first thing that can be done is to improve the status message. At the moment, before launch detection, the message is autolaunch/ready (OSD alternately displays the words 'autolaunch' and 'ready'). My brain saw the word 'autolaunch' and thought "ah good, yes, I'm autolaunching, all ok". Then the OSD flashes 'ready' and my brain thought "ah good, ready==good, all ok". At no point did my brain go *red alert* *red altert* *launch not triggered*. An improvement would be "waiting"/"for launch". Normally, waiting==bad, e.g. waiting for gps fix. "for launch" suggests something is not right with launch.
2. Use of additional sensors. For example, if baro or gps detects a height gain above some configured value, then the fc should consider itself as airborne (maybe also if it had moved some horizontal distance as well).
3. Bad pilot habit. I had become over-reliant on using stick movement to end autolaunch instead of switching off autolaunch via say an aux switch (which would have given my back control). I don't think this is even an option if autolaunch is enabled as a feature.
4. There are probably other things that I haven't thought of.

## Who does this impact? Who is this for?
Autolaunch users.

## Additional context
FB group thread:
https://www.facebook.com/groups/INAVOfficial/posts/1276936489415666/

**Comment by MrD-RC** [comment]
**2**
Which version of iNav are you using? 2 is already implemented in 3.0 https://github.com/iNavFlight/inav/pull/6726

**1**
I don’t really think the system messages for autolaunch are bad. If I see **READY**, I read it as iNav is ready to do something. As in, it hasn’t yet but is waiting to do so. Ready doesn’t mean that it’s doing something, it means that everything is OK to do something. So the message is correct. The message shouldn’t suggest that something is bad, as there isn’t anything bad. 

But, just **READY** isn’t quite so clear. Ready for what? Perhaps changing the wording to **READY TO LAUNCH** would be clearer and more explicit. The word __to__ in there, also backs up that the launch hasn’t been detected. 

**3**
Stick movement to end the launch sequence. The only issue I have with this, is that if you have raised the throttle, exiting launch will output that throttle value instantly. This is why it’s better to demand a low throttle or disarm before exiting launch mode after the throttle has been raised. It is a safety thing

Ultimately, I believe that the launch detection sanity checking should be performed by **2**. This should be in iNav now. So the issue may be that this needs some fine tuning.

**Comment by MrD-RC** [comment]
**1**
The issue I have with **WAITING FOR LAUNCH** is that it can also be misconstrued that auto launch isn't ready yet. It is ready, it's just waiting for you to throw the plane. It is green for go. There has just been a problem with the go part. That's why I think **READY TO LAUNCH** would be the best option. If you see that, you don't think that it __is__ launching, and there's no ambiguity as to what it's waiting for.

**2**
I see the problem. But, personally, I don't get why people don't use iNav with GPS. A cheap BN-220 is all that's needed, and it opens up more features and information; even if you don't want to use the autopilot stuff. However, what if the GPS fails on launch and the launch is not detected. Another edge case maybe. 

The issue with the baro/altitude is how to calculate the detection. 
- How high can X model climb on idle throttle? Does it even climb, or is it just enough to maintain altitude and fly away. This will always be different from plane to plane, as well as depending on the settings.
- How high was it thrown? You don't want it to trigger too early, it needs to be away from the pilot.
- Where is the relative height calculated from, as we don't know when the throw attempt happened?
- Is the baro suffering from drift?

Ultimately, this is why the GPS was used. It can determine a non-triggered launch much more precisely.

**3**
No problem. Suggestions are always helpful, and I totally get where you're coming from. I was in agreement until I remembered an incident I had a few years back. Ultimately though, this can't happen due to safety. For example, someone enabled launch, arms, raises the throttle, then accidentally bumps the aileron. That motor will instantly go to the stick throttle level, which could end up cutting the pilot badly. Some people have an idle delay, and put their transmitter down before throwing the model. So that situation could be very real.

**Comment by breadoven** [comment]
The other possibility here is to allow the launch to be cancelled by moving the sticks with the throttle NOT low but only if idle launch throttle has been set and the throttle stick position is no higher than the idle setting + some margin perhaps. Seems to me that if the "idle" launch throttle set is sufficient to keep the plane aloft it's already generating reasonable thrust so the safety issue with the motor suddenly starting when the launch is cancelled using the sticks isn't such a problem.

**Comment by MrD-RC** [comment]
There is still a chance of bumping sticks before launching though. While the idle throttle is already spinning the prop, so you are aware of it. If you accidentally exit launch mode before throwing, there is no warning. This could result in failed launches. 

So would this lock the throttle to idle? Or is it reliant on the throttle stick position? Only people usually set the throttle stick to post-launch cruise throttle, which could be higher than idle in a good percentage of cases. Could iNav exit the launch mode, but keep the throttle at idle, regardless of where the throttle setpoint is. Then if the throttle is lowered and raised, the pilot regains control of the throttle. That way they can continue the flight, not just land on idle and launch again.

**Comment by breadoven** [comment]
This reverts to the throttle set by the stick position if aborted. Abort won't work if the stick position is set higher than launch idle throttle but I'm thinking the launch idle must be fairly high to keep the plane flying so maybe this would work in most cases where the plane has enough "idle" throttle to fly off. There is also the possibility of allowing a higher throttle stick setting than launch idle throttle, by some margin that doesn't result in too significant an increase in thrust if aborted.

I don't think accidentally aborting by knocking the sticks before launch is much different to the current situation. Launch can be accidentally aborted now if it's set as a feature and you knock the sticks before raising the throttle. And it can also be accidentally aborted immediately after launch is detected cancelling it close to the ground, it's always a risk if you're careless with the transmitter. It should be obvious it's aborted prior to launch by the beeper stopping, launch OSD messages disappearing and control surfaces resetting.

This is more about avoiding an out of control plane continuing to fly than saving the plane itself and also the fact that people instinctively try and use the pitch/roll stick to regain control and probably even raise the throttle rather than lowering it. Remembering to lower the throttle instead to regain control when in panic mode is counter intuitive.

**Comment by Mateyhv** [comment]
Isn't the launch aborted by just flicking the launch switch to off? This won't work for autolaunch always on but this feature has some serious drawbacks and safety hazards so I dont really encourage using it.

**Comment by b14ckyy** [comment]
Fixed with gps speed trigger and new Autolaunch messages a while ago.
