### ISSUE TITLE
Quad is moving with out input 

### ISSUE THREAD

**Issue by Urben2006** [iNavFlight/inav#7792]
## Current Behavior
The drone moves with out input after a small punch out, see below video that shows the issue. 

Im seeing the same issue in two different drones (3 inches and 7 inches). One quad has inav 3.0 and the other one 4.0

https://user-images.githubusercontent.com/98786067/151892345-9e0fdeb3-b8cd-4042-86d5-7bc3570aec64.MOV

Both quads are in stock inav no change has been made. 

## Steps to Reproduce

1. Do a short punch out
2. Lower the throtle to 0 
3. The drone will move by itself. 

## Expected behavior
Drone should not move with out input

- FC Board name and vendor: matek H7 mini
- INAV version string: 4.0

**Comment by pitts-mo** [comment]
Hello @Urben2006,
Your description and video appears to be completely normal behavior motor idle speed set to low and AIR mode disabled. Multirotor props need to maintain a minimum RPM while armed and use of AIR mode allows the craft to maintain orientation extremely well.

Check that air mode is enabled and test again.
If problem persists maybe try to provide black box and/or provide a recording that includes the audio.


Additional info:
I have only utilized INAV on planes and mainly utilize betaflight on quads where I think AIR mode is typically on by default... On my quads I disable AIR mode to make take of and landings safer. However, I then use a three position switch for arming so I can have disarmed, armed, and armed with AIR mode.  Note: If you use ELRS you should off-set the throw a little so that ELRS reliably detects ARMED state while the switch is in the center position.
