### ISSUE TITLE
GPS ground course not straight in 3D cruise mode

### ISSUE THREAD

**Issue by wilco1967** [iNavFlight/inav#8557]
As requested, made a new issue

iNav version
# INAV/MATEKF405SE 6.0.0 Oct 20 2022 / 15:20:51 (d1f6f19a)

Airplane: Mini Crosswind
very slight wind

Attached, BB log
[LOG00048.zip](https://github.com/iNavFlight/inav/files/10006531/LOG00048.zip)

-----from original post,  see #8529 --------------
 Not sure if this is related, but yesterday I made some flights using 6.0.0. FP1 release.

in WP mode, using nav_fw_wp_tracking_accuracy = 5, the plane flew the sections between WP's perfectly. 

But when flying in 3d cruise mode, the plane often makes strange uncommanded sudden 'corrections' to it's heading. 
Also, the telemetry heading often seems off from the actual course over ground. perhaps 10..20 deg.
It seems like, when the indicated heading deviates too much, it makes a correction.

When supposed to fly a straight line, the actual heading over ground slowly changes, making a very slight curve. then at some point, it makes a sudden correction to come back to the intended header.  The general direction is maintained alright, just these occasional corrections (like 20..60 sec apart).

here's a view from google earth of actual track (EdgeTx telemetry). This was supposed to be a straight line.

![image](https://user-images.githubusercontent.com/4282983/201724820-095239ed-fb84-489c-a2c3-3bb0439a3a68.png)

It also seems to affect RTH mode. when RTH is activated, it goes into the general direction of 'home', but it's not 100% accurate (perhaps 10 deg off, but not consitent). After some time, it makes a sudden correction to where it needs to go. It comes back home fine, but just not in a perfectly straight line.

note the (right) yellow line (yellow = RTH). notice the sudden correction.
![image](https://user-images.githubusercontent.com/4282983/201728308-30cd5461-10d5-418d-a799-9d9f0c38e077.png)

The white/grey points are WP mode. This is perfect....

There was hardly any wind during the flight (less then 10 km/h).

I'm guessing, this may be a side effect from the WP tracking option ?

in iNav 5.1, it flew perfectly straigt line in 3d cruise.

The plane has no compass. GPS heading only.

**Comment by breadoven** [comment]
This likely caused by the new AHRS wind compensation affecting the heading. The reason it resets at regular intervals is due to the fact Course Hold actually sets a waypoint to head towards rather than trying to follow a course heading. The waypoint is repeatedly set 60 seconds distance ahead based on current speed over the ground on the Course Hold bearing that was set when the mode was switched on or last adjusted. You end up with a curved path between waypoints because the AHRS wind compensated estimated heading is unlikely to match the actual heading leading to heading drift. Turning off `imu_gps_yaw_windcomp ` should confirm this.

This wasn't a problem before for a fixed wing without a compass because heading was essentially just GPS ground course, so less/unaffected by wind drift.

Also WP tracking accuracy doesn't affect Course Hold so wouldn't be the reason for the curvy tracks.
