### ISSUE TITLE
Add support for all external Mag orientations

### ISSUE THREAD

**Issue by piposa** [iNavFlight/inav#86]
Align_sensors() has just support for mag orientations if mag is mounted on board. Missing is support if the flight controller board is mounted perpendicular to Mag/GPS board and external mag is used.
Extend align_mag with additional orientations.

**Comment by digitalentity** [comment]
That's rather exotic configuration. I'm not sure if it's worth the effort. I'll keep the issue open for the time being to keep track of the idea.

**Comment by piposa** [comment]
I you limit your view to copters, I agree it is a quite exotic configuration. 
I use a FLIP mini in flying wing and I have mounted it verticaly in the wing to have easy access to the usb port.
For airplanes the fuselage often allows easier mounting below the cockpit canopy so that the usb port is accessable from the top. Avoids extension cords or additional openings in the fuselage.
I solve that for now by hand modifying the code prior to compile. I agree extending the switch () statement for all possibilities is too much. Right now I lack a better idea, but could it be done as a kind of matrix? The human readable configuration should be done in the configurator... Not exactly sure how....

**Comment by brainbubblersbest** [comment]
Can you post a short howto?
eg if i use a BN880 with cw270 mounted compass
What Values do i need to set if the BN880 is mounted with arrow pointing forward.

And now in addition: Tilt it Backwards because it is mounted on a 30 Degree Cam mount.

Does "as well as the board alignment are ignored" mean Orientation is relative to Flight Direction and not FC Position now?

This Example is seen a few Times and Users are Confused what is to set here.
Thank you.
