### ISSUE TITLE
Home point updated by RC Control with an internal GPS Module (TX16s, etc)

### ISSUE THREAD

**Issue by rodrigosclosa** [iNavFlight/inav#8922]
## Current Behavior

Sometimes we need to take off the drone without the GPS having fixed it, or the GPS may take a long time to fix it in some situations and places. It would be very useful to be able to use the Control's GPS position (if it has an internal GPS module) as the Home's return point.

## Desired Behavior

If the Pilot Control has an internal GPS module, use these coordinates as the Home return point when RTH is activated.

## Suggested Solution

A way to send the Control's GPS coordinates to the iNav via the RC link. Allow the pilot to configure if he wants to use the Control coordinates, the Drone or not let it arm without fixing the GPS.

## Who does this impact? Who is this for?

Fixed Wings and Multirotor pilots

**Comment by stronnag** [comment]
The FC already has the capability to do this. All you have to do is implement it on the radio; just a small matter of programming.
Solutions are described on the wiki, https://github.com/iNavFlight/inav/wiki/INAV-Remote-Management,-Control-and-Telemetry#follow-me-gcs-nav and https://github.com/iNavFlight/inav/wiki/Navigation-modes#gcs_nav---ground-control-station.
No further work is needed in firmware, the `GCS_NAV` has existed since c. 2016.
