### ISSUE TITLE
NAV - add cross track error support for FW

### ISSUE THREAD

**Issue by csurf** [iNavFlight/inav#90]
more info:
http://www.rcgroups.com/forums/showpost.php?p=10263920&postcount=12
http://diydrones.com/forum/topics/anyone-knows-how-to-measure-the-lateral-crosstrack-error

**Comment by digitalentity** [comment]
Good idea, thanks

**Comment by digitalentity** [comment]
This won't happen in 1.2 sorry.

**Comment by oleost** [comment]
@digitalentity Postpone to 2.0 ?

**Comment by digitalentity** [comment]
I doubt this will happen any time soon. This is really low priority :smile:

**Comment by breadoven** [comment]
This is effectively dealt with by https://github.com/iNavFlight/inav/pull/8234 so this can be closed. Could rename `distToCourseLine  `parameter to "cross track error" since this is what it is in fact. Could also be made available as a `posControl `parameter although I'm not sure what use it has other then for display on the OSD perhaps.
