### ISSUE TITLE
TcmmRC f4 com giroscópio bmi270

### ISSUE THREAD

**Issue by Flightnew** [iNavFlight/inav#9241]

**Comment by Flightnew** [comment]
Hi, I have a Aliexpress TcmmRc F4 with gyroscope bmi270 or bmi160 (can't define exactly).
On BETAFLIGHT the board is called Matek f405, but INAV do not have such a board. The gyroscope is not detected on the INAV Matek f405 firmware. Is there any board I could choose to flash INAV on it to make everything work.

**Comment by MrD-RC** [comment]
Sounds like a clone board who are piggybacking off the original target. The problem is when the changes components to those not supported by the original hardware.

What should really happen is that TcmmRc should submit their own target for their flight controller, and maintain that. https://github.com/iNavFlight/inav/blob/master/docs/policies/NEW_HARDWARE_POLICY.md

**Comment by Flightnew** [comment]
olá, ela utiliza o firmwre da Matek 405. Existe a TcmmRc F4 com mpu 6000
