### ISSUE TITLE
Elevon movement not equal

### ISSUE THREAD

**Issue by nicesub** [iNavFlight/inav#9376]
Hello,

I am posting this issue here in hope I finally find the solution to the problem of my first INAV build. 
I am building AtomRC Dolphin and I am having issues with elevons not reaching same level of deflection. I have even replaced servos and the issue persists. ON the bench when I push my sticks forward the left side moves up more by 4mm then the right side. When I pull back on the stick they are equal.
All of the testing is done in manual mode with default mixer values and output values. The only thing I adjusted is midpoints. 
I tried swapping servo outputs on the FC and the issue follows. 
FC in question is Matek H743WLITE. 
Honestly I do not know what else should I do or if this is normal quirk of the INAV that will get trimmed out and auto tunned in maiden.

**Comment by MrD-RC** [comment]
This sounds like a physical setup issue to me.

Set the midpoints back to 1500. Then try to get the servo horns in about the same place each side, ideally 90 degrees to the control rod. If the splines don't allow the servo horns to come out at 90 degrees, slightly forwards is better. Then adjust the linkages so that the control surface is level with the trailing edge of the wing. Those areas are quite floppy, so make sure that part of the wing also lines up with the profile on the fuselage. If they are the same holes each side, you should get similar throw.
