### ISSUE TITLE
Inav 7.0 autolevel issue

### ISSUE THREAD

**Issue by fatbaldmen** [iNavFlight/inav#9615]
## Current Behavior

 as of inav 7.0, autolevel will pitch up or down when autolevel is enabled. Sometimes the pitch up or down is hard, or soft. Making the tunning process very hard. Aircraft will not maintain level flight regardless of how long auto level is enabled. Pre inav 7, auto levelworked just fine

 !-- Steps to reproduce the behavior: -->
1. Attempted to fly inav 7 on different Flight controllers. All producing the same issue
2. Word of mouth from some of the other inav testers that this is also happening to them.
3.Created a post in the inav fixed wing Facebook group, asking if anyone else has had this issue. 
4.

## Expected behavior

auto level should work as planned. Enabled autolevel, fly hands off for a short while, or until Aircraft maintains level flight..

## Suggested solution(s)

 For someone smarter than me to look at the code for possible abnormalities.

## Additional context

---

- FC Board name and vendor: Matek F411-wte, SpeedyBee F405 wing 
- INAV version string: Inav 7.0 stable, with inav 7.01 configurator

**Comment by breadoven** [comment]
What value do you have for `fw_level_pitch_gain `?

There was bug with auto level which theoretically would have prevented it working properly if at all. It's possible it did work just very slowly. This bug was fixed in 7.0 which possibly would have made it a lot more responsive than before. Reducing the above setting should settle the response if it's causing problems.

**Comment by fatbaldmen** [comment]
@breadoven 

FW_LEVEL_PITCH_GAIN = 5.00
