### ISSUE TITLE
No GPS Fix with BEITIAN BN-180/220 on Inav 7.0.1

### ISSUE THREAD

**Issue by blooddog70** [iNavFlight/inav#9707]
Hi, I have a problem with my Beitian BN-180/220 with INAV 7.0.1! I'm currently building my first wing, I already have several copters with BF running with the above-mentioned GPS. But I can't get any satellites with INAV, everything is connected correctly, the GPS symbol lights up blue, GPS is activated, the correct UART is assigned to the Ports tab, and I've already tried all of the baud rates. Protocol is UBLOX selected, Ground Assistance Type European EGNOS, GPS use GALILEO SATTELITES (EU), TimeZone Offset +01:00, AUTOMATIC DAYLIGHT SAVING MODE is EU. It also counts up the TOTAL MESSAGES, UPDATE TIME 5.00 Hz mostly, No ERRORS or TIMEOUTS. I have no idea what else I should try to make it work. Does anyone have an idea? Thanks in advance for all the helpful answers.

Status say that in CLI:

![Screenshot_2024-02-03_152610](https://github.com/iNavFlight/inav/assets/89160860/8f9ee548-2334-4920-9102-cf90923ca381)

**Comment by MrD-RC** [comment]
@sensei-hacker has basically summed everything up. Once the almanac downloads, things will speed up. If you don’t get any satellites outside after 20 minutes. You may want to try a different module. Maybe the antenna is faulty or there is a problem with the module. 

The communication between INAV and the GPS module is fine. I would recommend using UBLOX7 rather than UBLOX.

**Comment by blooddog70** [comment]
ok and which baudrate should I take in the Ports Tab? 9600? OK i will test UBLOX7, why is it better to UBLOX Protocol?
I tested 3 different Modules, VTX antenna is far away....

**Comment by blooddog70** [comment]
Should i do that:

https://30081112.s21i.faiusr.com/61/ABUIABA9GAAg0oPEpAYotI7PdA.pdf

**Comment by MrD-RC** [comment]
115200

**Comment by dekakrens** [comment]
I have the same problem. I use Flywoo Goku GM10 nano v3 and MicoAir M10G, both of them hard to get GPS lock with INAV 7.1. Also, I tried to update to INAV 8 and the problem is still there. Even if I get locks, and then I fly the GPS lock is gone. I know my GPS module is fine because I also tested it on other quads running betaflight and never had this problem. I also mount the GPS far from other interferences like VTX antenna, the wire is also shielded and grounded to provide more signal integrity. Is there anything else I can try? I really want to fly INAV and have plan to build fixed wing with INAV

**Comment by sensei-hacker** [comment]
> I have the same problem. I use Flywoo Goku GM10 nano v3 and MicoAir M10G, both of them hard to get GPS lock with INAV 7.1.

You are testing outdoors, right? After downloading the almanac and emperides for at least 12.5 minutes? The M10 doesn't have flash to save things like the M8 and M9 do, so it can be slower on warm starts.

Please show us the configuration in the GPS tab and how you have things mounted.
